// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const phoneHomeBurple: TemplateDefinition = {
  "themeId": "phone-home",
  "cards": [
    {
      "card_type": "hero",
      "title": "LISTEN",
      "description": null,
      "url": null,
      "content": {
        "iconName": "Music",
        "textAlign": "center",
        "appIconUrl": "/icons/mac/happy-mac.png",
        "showButton": false,
        "wordArtStyle": "style-four",
        "phoneHomeLayout": {
          "col": 2,
          "row": 3,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "small",
      "position": "center",
      "sortKey": "a0",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": "VIDEOS",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "textAlign": "center",
        "appIconUrl": "/icons/mac/floppy.png",
        "showButton": false,
        "wordArtStyle": "style-seven",
        "phoneHomeLayout": {
          "col": 1,
          "row": 0,
          "page": 1,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "small",
      "position": "center",
      "sortKey": "a1",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "TOUR DATES",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "appIconUrl": "/icons/mac/appleshare.png",
        "wordArtStyle": "style-twentyone",
        "phoneHomeLayout": {
          "col": 0,
          "row": 5,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a2",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "MERCH",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "appIconUrl": "/icons/mac/font-suitcase.png",
        "wordArtStyle": "style-fourteen",
        "phoneHomeLayout": {
          "col": 1,
          "row": 3,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a3",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "YOUTUBE",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "appIconUrl": "/icons/mac/warning.png",
        "wordArtStyle": "style-three",
        "phoneHomeLayout": {
          "col": 1,
          "row": 5,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a4",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "WEBISTE",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "appIconUrl": "/icons/mac/sad-mac.png",
        "wordArtStyle": "style-one",
        "phoneHomeLayout": {
          "col": 3,
          "row": 3,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a5",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "DEMOS",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "appIconUrl": "/icons/mac/trash-full.png",
        "wordArtStyle": "style-one",
        "phoneHomeLayout": {
          "col": 0,
          "row": 3,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a6",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "macLinks": [
          {
            "url": "https://open.spotify.com/album/",
            "title": "LISTEN"
          },
          {
            "url": "https://bandsintown.com/",
            "title": "VIDEOS"
          },
          {
            "url": "https://bandsintown.com/",
            "title": "TOUR DATES"
          },
          {
            "url": "https://bandsintown.com/",
            "title": "MERCH"
          }
        ],
        "notepadStyle": "buttons",
        "macWindowStyle": "notepad"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a7",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": "LINK OR VIDEO",
      "description": null,
      "url": null,
      "content": {
        "macMode": "link",
        "macTextAlign": "left",
        "macTextColor": "#000000",
        "macWindowStyle": "small-window",
        "macCheckerColor": "#cfffcc",
        "macWindowBgColor": "#afb3ee"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a8",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": "LINK OR VIDEO",
      "description": null,
      "url": null,
      "content": {
        "macMode": "link",
        "macTextAlign": "left",
        "macTextColor": "#000",
        "macWindowStyle": "small-window",
        "macCheckerColor": "#cfffcc",
        "macWindowBgColor": "#afb3ee"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a9",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "calcMessage": "custom message ",
        "macWindowStyle": "calculator"
      },
      "size": "big",
      "position": "left",
      "sortKey": "aA",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "macWindowStyle": "map"
      },
      "size": "big",
      "position": "left",
      "sortKey": "aB",
      "is_visible": false
    },
    {
      "card_type": "audio",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "tracks": [],
        "looping": false,
        "autoplay": false,
        "reverbConfig": {
          "mix": 0.3,
          "damp": 0.5,
          "width": 0.8,
          "enabled": false,
          "roomSize": 0.5,
          "predelayMs": 20
        },
        "showWaveform": true,
        "blinkieColors": {
          "text": "#000000",
          "buttons": "#f1c2ff",
          "innerBox": "#f1c2ff",
          "outerBox": "#d3a3e1",
          "playerBox": "#c497d2"
        },
        "phoneHomeLayout": {
          "col": 0,
          "row": 0,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "blinkieBoxBackgrounds": {
          "cardBgNone": true,
          "cardOuterDim": 9
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "aC",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/media-player.png",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 0,
          "row": 0,
          "page": 1,
          "width": 1,
          "height": 1
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "aD",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "albumArtUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/9b437c15-d956-4b88-9b2e-3c1681fec566/85a9c56a-9544-41db-b943-26d16c0610cb.jpg",
        "showCountdown": true,
        "macWindowStyle": "presave",
        "presaveBgColor": "#F2FFA4",
        "preSaveButtonText": "Pre-save",
        "afterCountdownText": "OUT NOW",
        "albumArtStoragePath": "9b437c15-d956-4b88-9b2e-3c1681fec566/85a9c56a-9544-41db-b943-26d16c0610cb.jpg",
        "afterCountdownAction": "custom"
      },
      "size": "big",
      "position": "left",
      "sortKey": "aE",
      "is_visible": false
    },
    {
      "card_type": "link",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/folder.png",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 2,
          "row": 4,
          "page": 1,
          "width": 1,
          "height": 1
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "aF",
      "is_visible": true
    },
    {
      "card_type": "music",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "title": "Plantasia",
        "autoplay": true,
        "embedUrl": "https://open.spotify.com/track/2XV5CUyw7gPVi18d718D4f?si=ae0c67787b3f4c0c",
        "platform": "spotify",
        "appIconUrl": "/icons/mac/sound.png",
        "embeddable": true,
        "thumbnailUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e028f06939f22ae1590f569c644",
        "embedIframeUrl": "https://open.spotify.com/embed/track/2XV5CUyw7gPVi18d718D4f?si=ae0c67787b3f4c0c&theme=0",
        "phoneHomeLayout": {
          "col": 0,
          "row": 2,
          "page": 1,
          "width": 4,
          "height": 2
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "aG",
      "is_visible": true
    },
    {
      "card_type": "gallery",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "images": [
          {
            "id": "fb09a2e6-8f2f-405f-bdca-156c7e0bd346",
            "alt": "brat-text-1771845085649",
            "url": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/5d70ce1f-d4de-4234-a55a-7876be7512fe/37ab3f89-d0af-4345-a6c8-aef92cc59339.png",
            "storagePath": "5d70ce1f-d4de-4234-a55a-7876be7512fe/37ab3f89-d0af-4345-a6c8-aef92cc59339.png"
          },
          {
            "id": "6afc3b46-e19c-41d3-b77c-f1f529df27f2",
            "alt": "brat-text-1771845206376",
            "url": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/5d70ce1f-d4de-4234-a55a-7876be7512fe/f6083ef0-b0b3-41df-8f94-cfc9b3c732b6.png",
            "storagePath": "5d70ce1f-d4de-4234-a55a-7876be7512fe/f6083ef0-b0b3-41df-8f94-cfc9b3c732b6.png"
          },
          {
            "id": "10d385dd-63bc-4570-9012-792c80092c3b",
            "alt": "brat-text-1771845241340",
            "url": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/5d70ce1f-d4de-4234-a55a-7876be7512fe/a2ea4f46-813d-4f63-9812-fa07f03e00bc.png",
            "storagePath": "5d70ce1f-d4de-4234-a55a-7876be7512fe/a2ea4f46-813d-4f63-9812-fa07f03e00bc.png"
          }
        ],
        "phoneHomeLayout": {
          "col": 2,
          "row": 0,
          "page": 1,
          "width": 2,
          "height": 2
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "aH",
      "is_visible": true
    }
  ],
  "theme": {
    "themeId": "phone-home",
    "paletteId": null,
    "colors": {
      "link": "oklch(0.62 0.22 250)",
      "text": "#ffffff",
      "accent": "oklch(0.62 0.22 250)",
      "border": "#000000",
      "cardBg": "#cba0d8",
      "background": "#a3b0c4"
    },
    "fonts": {
      "body": "var(--font-geist-sans)",
      "heading": "var(--font-geist-sans)",
      "bodySize": 0.85,
      "headingSize": 1,
      "headingWeight": "normal"
    },
    "style": {
      "borderRadius": 16,
      "blurIntensity": 0,
      "shadowEnabled": false
    },
    "background": {
      "type": "image",
      "value": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/36eb6d57-7a64-458a-aafa-16e076ead485/backgrounds/1771755969033.jpeg",
      "dimOverlay": false,
      "glitchType": "crt",
      "topBarColor": "#c497d2",
      "dimIntensity": 25,
      "glitchEffect": false,
      "noiseOverlay": false,
      "glitchFullPage": false,
      "glitchRgbShift": 75,
      "noiseIntensity": 15,
      "glitchCrtPreset": "computer-monitor",
      "glitchIntensity": 10,
      "glitchPixelSize": 6,
      "glitchCrtFlicker": false,
      "glitchPixelShape": "cross",
      "glitchCrtCurvature": 0,
      "glitchCrtLineSpeed": 65,
      "glitchCrtScanlines": 85,
      "glitchDigitalNoise": 0,
      "glitchInterference": 25,
      "glitchCrtAberration": 65,
      "glitchCrtBrightness": 110,
      "glitchPixelBitDepth": "1-bit",
      "glitchPixelDirection": "square",
      "glitchPixelDithering": "bayer",
      "glitchCrtLineMovement": true,
      "glitchCrtPhosphorGlow": 100,
      "glitchCrtLineDirection": "left",
      "glitchLineDisplacement": 5,
      "glitchCrtFlickerIntensity": 5,
      "glitchCrtScanlineThickness": 100
    },
    "cardTypeFontSizes": {
      "hero": 0.8,
      "square": 1,
      "horizontal": 1,
      "link": 1.2,
      "mini": 1,
      "text": 1,
      "gallery": 1,
      "video": 1
    },
    "centerCards": false,
    "vcrCenterContent": false,
    "receiptPrice": "PRICELESS",
    "receiptStickers": [],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": false,
    "ipodStickers": [],
    "ipodTexture": "/images/ipod-texture-scratched.jpeg",
    "ipodFont": "system",
    "macPattern": "/images/mac-patterns/pattern-1.png",
    "macPatternColor": "#7e350d",
    "wordArtTitleStyle": "style-three",
    "phoneHomeDock": [
      "a4",
      "a2",
      "a1"
    ],
    "phoneHomeShowDock": true,
    "phoneHomeDockTranslucent": true,
    "phoneHomeVariant": "8-bit",
    "zineBadgeText": "NEW!",
    "zineTitleSize": 1,
    "zineShowDoodles": true,
    "artifactMarqueeText": "LINKS_DATABASE /// ACCESS_GRANTED >>> CONNECT_NOW /// NET_RUNNER",
    "artifactHeaderTopLeft": "USER.ID_99",
    "artifactHeaderTopCenter": "[ONLINE]",
    "artifactHeaderTopRight": "",
    "artifactHeaderBottomLeft": "DIGITAL // PHY",
    "artifactHeaderBottomCenter": "///",
    "artifactHeaderBottomRight": "SYS_ADMIN",
    "artifactShowHeaderMeta": true,
    "artifactHeroOverlay": true,
    "artifactHeroMediaType": "image",
    "artifactHeroImageUrl": "",
    "artifactHeroVideoUrl": "",
    "artifactHeroPositionX": 50,
    "artifactHeroPositionY": 50,
    "scatterMode": false,
    "visitorDrag": false
  },
  "profile": {
    "displayName": "YOUR NAME",
    "bio": null,
    "avatarUrl": null,
    "avatarFeather": 0,
    "showAvatar": true,
    "showTitle": true,
    "titleSize": "small",
    "showSocialIcons": true,
    "showLogo": false,
    "logoUrl": null,
    "logoScale": 100,
    "profileLayout": "classic",
    "headerTextColor": "#ffffff",
    "socialIconColor": "#ffffff",
    "socialIcons": [
      {
        "id": "86ec3c07-a25a-4aaf-b063-98ae75cf1fa8",
        "url": "",
        "sortKey": "a1",
        "platform": "instagram"
      },
      {
        "id": "144c3a93-9040-471f-86d9-cacda54921ff",
        "url": "",
        "sortKey": "a2",
        "platform": "spotify"
      },
      {
        "id": "8d4ad2df-d302-4e46-a9f6-a4f19633c261",
        "url": "",
        "sortKey": "a3",
        "platform": "tiktok"
      }
    ]
  },
  "mediaAssets": [],
  "id": "phone-home-burple",
  "name": "BURPLE",
  "description": "BURPLE template",
  "thumbnailPath": "/templates/phone-home-burple/thumbnail.jpg"
} as const satisfies TemplateDefinition
