// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const phoneHomeMclovinsIphone: TemplateDefinition = {
  "themeId": "phone-home",
  "cards": [
    {
      "card_type": "link",
      "title": "LINK",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/winamp.png",
        "wordArtStyle": "style-five",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 2,
          "row": 2,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a0",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "LINK",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/winamp.png",
        "wordArtStyle": "style-five",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 0,
          "row": 2,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a0V",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "LINK",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/my-documents.png",
        "wordArtStyle": "style-five",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 0,
          "row": 1,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a0l",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "LINK",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/sound.png",
        "wordArtStyle": "style-five",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 1,
          "row": 2,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a0t",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "LINK",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/pinball.png",
        "wordArtStyle": "style-five",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 0,
          "row": 1,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a0x",
      "is_visible": true
    },
    {
      "card_type": "square",
      "title": "LINK",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/my-computer.png",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 3,
          "row": 4,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "small",
      "position": "left",
      "sortKey": "a1",
      "is_visible": true
    },
    {
      "card_type": "square",
      "title": "LINK",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/internet-explorer.png",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 3,
          "row": 2,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "small",
      "position": "left",
      "sortKey": "a2",
      "is_visible": true
    },
    {
      "card_type": "gallery",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "images": [
          {
            "id": "e92c6bef-bc5a-48be-85be-52be637888a4",
            "alt": "_ (22)",
            "url": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/dd2cae07-d38a-4a6d-b043-0f8a36407c2a/e01ee20c-a2ba-4f73-8ebf-d5f08ed09f73.jpg",
            "storagePath": "dd2cae07-d38a-4a6d-b043-0f8a36407c2a/e01ee20c-a2ba-4f73-8ebf-d5f08ed09f73.jpg"
          }
        ],
        "galleryStyle": "carousel",
        "phoneHomeLayout": {
          "col": 0,
          "row": 0,
          "page": 0,
          "width": 4,
          "height": 2
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "a3V",
      "is_visible": true
    },
    {
      "card_type": "audio",
      "title": "PLAYER",
      "description": null,
      "url": null,
      "content": {
        "tracks": [
          {
            "id": "f8bc85ad-22b8-43d5-9aef-c330698751e8",
            "title": "LEASE ",
            "artist": "Takeshi Abo ",
            "audioUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-audio/cead228f-f7b6-429e-a2f3-76fc273e66c1/f8bc85ad-22b8-43d5-9aef-c330698751e8.mp3",
            "duration": 103.340417,
            "albumArtUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/644a69ab-10dc-4790-bdd4-a24f62d5cb0b/9c3d6ea4-41dd-4eab-a7df-a7d4d16ab796.jpg",
            "albumArtStoragePath": "644a69ab-10dc-4790-bdd4-a24f62d5cb0b/9c3d6ea4-41dd-4eab-a7df-a7d4d16ab796.jpg",
            "originalAlbumArtUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/644a69ab-10dc-4790-bdd4-a24f62d5cb0b/9f7a327b-46ac-4dd3-9b43-df478c3430c4.jpg"
          }
        ],
        "looping": false,
        "playerStyle": "cd-player",
        "reverbConfig": {
          "mix": 0.3,
          "damp": 0.5,
          "width": 0.8,
          "enabled": false,
          "roomSize": 0.5,
          "predelayMs": 20
        },
        "showWaveform": true,
        "blinkieColors": {
          "text": "#ccc0e0",
          "buttons": "#a84888",
          "innerBox": "#6a4898",
          "outerBox": "#1a1530",
          "playerBox": "#483570"
        },
        "phoneHomeLayout": {
          "col": 0,
          "row": 5,
          "page": 0,
          "width": 4,
          "height": 3
        },
        "phoneHomeWidgetMode": true,
        "blinkieBoxBackgrounds": {
          "cardBgUrl": "/card-backgrounds/green-orbits.gif"
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a4",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "LINK",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/folder.png",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 0,
          "row": 4,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a5",
      "is_visible": true
    },
    {
      "card_type": "music",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "title": "Take Da Charge",
        "embedUrl": "https://open.spotify.com/track/2XOKoaCWziW0W14DPeY7XS?si=b551f5abeb964d19",
        "platform": "spotify",
        "appIconUrl": "/icons/8bit/8bit46.png",
        "embeddable": true,
        "thumbnailUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02393fb413d09de1443185da1e",
        "embedIframeUrl": "https://open.spotify.com/embed/track/2XOKoaCWziW0W14DPeY7XS?si=b551f5abeb964d19&theme=0",
        "phoneHomeLayout": {
          "col": 0,
          "row": 5,
          "page": 1,
          "width": 4,
          "height": 2
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a6",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/find-file.png",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 0,
          "row": 0,
          "page": 1,
          "width": 1,
          "height": 1
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "a7",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "calcMessage": "idiot",
        "macWindowStyle": "calculator",
        "scatterLayouts": {
          "mac-os": {
            "x": 40,
            "y": 30.000000000000007,
            "width": 60,
            "height": 40,
            "zIndex": 5
          },
          "word-art": {
            "x": 40,
            "y": 30.000000000000007,
            "width": 60,
            "height": 40,
            "zIndex": 5
          },
          "macintosh": {
            "x": 40,
            "y": 30.000000000000007,
            "width": 60,
            "height": 40,
            "zIndex": 5
          },
          "instagram-reels": {
            "x": 40,
            "y": 30.000000000000007,
            "width": 60,
            "height": 40,
            "zIndex": 5
          },
          "system-settings": {
            "x": 40,
            "y": 30.000000000000007,
            "width": 60,
            "height": 40,
            "zIndex": 5
          }
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a7",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "macWindowStyle": "map",
        "scatterLayouts": {
          "mac-os": {
            "x": 0,
            "y": 60,
            "width": 60,
            "height": 40,
            "zIndex": 6
          },
          "word-art": {
            "x": 0,
            "y": 60,
            "width": 60,
            "height": 40,
            "zIndex": 6
          },
          "macintosh": {
            "x": 0,
            "y": 60,
            "width": 60,
            "height": 40,
            "zIndex": 6
          },
          "instagram-reels": {
            "x": 0,
            "y": 60,
            "width": 60,
            "height": 40,
            "zIndex": 6
          },
          "system-settings": {
            "x": 0,
            "y": 60,
            "width": 60,
            "height": 40,
            "zIndex": 6
          }
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a8",
      "is_visible": false
    },
    {
      "card_type": "link",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/media-player.png",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 2,
          "row": 3,
          "page": 1,
          "width": 1,
          "height": 1
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "a8",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/mail.png",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 0,
          "row": 4,
          "page": 1,
          "width": 1,
          "height": 1
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "a8G",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/help.png",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 1,
          "row": 2,
          "page": 1,
          "width": 1,
          "height": 1
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "a8V",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/network.png",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 3,
          "row": 4,
          "page": 1,
          "width": 1,
          "height": 1
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "a8l",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "macMode": "video",
        "macVideoUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-videos/01ec9b3e-c7fc-4722-87fd-3c388421b680/1a4185d0-4427-44fd-88ae-d0832e9860f3.mp4",
        "macTextAlign": "center",
        "macTextColor": "#ffffff",
        "macWindowStyle": "small-window",
        "macCheckerColor": "#8f5685",
        "macWindowBgColor": "#6895a1",
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a9",
      "is_visible": false
    },
    {
      "card_type": "music",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "embedUrl": "https://ppudc.bandcamp.com/album/liquid-deep-2",
        "platform": "bandcamp",
        "embeddable": true,
        "embedHeight": 42,
        "embedIframeUrl": "https://bandcamp.com/EmbeddedPlayer/album=4223445559/size=small/bgcol=ffffff/linkcol=0687f5/transparent=true/",
        "phoneHomeLayout": {
          "col": 0,
          "row": 5,
          "page": 0,
          "width": 4,
          "height": 1
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "a9",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": "BAkANI",
      "description": null,
      "url": null,
      "content": {
        "macMode": "link",
        "macTextAlign": "center",
        "macTextColor": "#000",
        "macWindowStyle": "small-window",
        "macCheckerColor": "#8f5685",
        "macWindowBgColor": "#6895a1",
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "aA",
      "is_visible": false
    },
    {
      "card_type": "gallery",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "images": [
          {
            "id": "53c7707d-1917-43ad-ae78-4a745a0c6c48",
            "alt": "_ (6)",
            "url": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/63cd75a7-95f7-4d06-903a-ca97c397445c/ecdf4ae7-286b-4c1b-85d2-6b6973b91227.gif",
            "originalUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/63cd75a7-95f7-4d06-903a-ca97c397445c/ecdf4ae7-286b-4c1b-85d2-6b6973b91227.gif",
            "storagePath": "63cd75a7-95f7-4d06-903a-ca97c397445c/ecdf4ae7-286b-4c1b-85d2-6b6973b91227.gif"
          }
        ],
        "phoneHomeLayout": {
          "col": 0,
          "row": 0,
          "page": 1,
          "width": 2,
          "height": 2
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "aA",
      "is_visible": true
    },
    {
      "card_type": "gallery",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "images": [
          {
            "id": "583994f0-48b8-4737-b9e5-1d96f2cd48a9",
            "alt": "Register - Login (1)",
            "url": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/63cd75a7-95f7-4d06-903a-ca97c397445c/5d81c711-3d55-4f3a-af5d-eea8999404c7.gif",
            "originalUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/63cd75a7-95f7-4d06-903a-ca97c397445c/5d81c711-3d55-4f3a-af5d-eea8999404c7.gif",
            "storagePath": "63cd75a7-95f7-4d06-903a-ca97c397445c/5d81c711-3d55-4f3a-af5d-eea8999404c7.gif"
          }
        ],
        "phoneHomeLayout": {
          "col": 2,
          "row": 1,
          "page": 1,
          "width": 2,
          "height": 2
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "aAV",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "macLinks": [
          {
            "url": "",
            "title": "LISTEN"
          },
          {
            "url": "",
            "title": "WATCH"
          },
          {
            "url": "",
            "title": "MORE"
          },
          {
            "url": "",
            "title": "PLAYER"
          }
        ],
        "notepadStyle": "buttons",
        "macWindowStyle": "notepad",
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "aB",
      "is_visible": false
    }
  ],
  "theme": {
    "themeId": "phone-home",
    "paletteId": null,
    "colors": {
      "link": "oklch(0.62 0.22 250)",
      "text": "oklch(1 0 0)",
      "accent": "oklch(0.62 0.22 250)",
      "border": "oklch(0.40 0 0 / 0.3)",
      "cardBg": "#3a462c",
      "background": "oklch(0.13 0 0)"
    },
    "fonts": {
      "body": "var(--font-geist-sans)",
      "heading": "var(--font-geist-sans)",
      "bodySize": 0.85,
      "headingSize": 1,
      "headingWeight": "normal"
    },
    "style": {
      "borderRadius": 16,
      "blurIntensity": 0,
      "shadowEnabled": false
    },
    "background": {
      "type": "image",
      "value": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/36eb6d57-7a64-458a-aafa-16e076ead485/backgrounds/1771462057818.jpeg",
      "dimOverlay": true,
      "topBarColor": "#3a462c",
      "dimIntensity": 10
    },
    "cardTypeFontSizes": {
      "hero": 0.6,
      "square": 1.4,
      "horizontal": 0.9,
      "link": 0.9,
      "mini": 1,
      "text": 1.3,
      "gallery": 1,
      "video": 1.8
    },
    "fontFamilyScales": {},
    "centerCards": false,
    "vcrCenterContent": true,
    "receiptPrice": "A GAJILLON ",
    "receiptStickers": [
      {
        "x": 4.765215498697749,
        "y": 1.4389843466185646,
        "id": "price-tag-2-1770970704453",
        "src": "/images/stickers/price-tag-2.jpeg",
        "scale": 1.0261351575739197,
        "rotation": 13.740950510664732,
        "behindText": false
      }
    ],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": true,
    "ipodStickers": [
      {
        "x": 48.73754500089153,
        "y": 91.25863511095115,
        "id": "price-tag-1-1770680564846",
        "src": "/images/stickers/price-tag-1.jpeg",
        "scale": 0.9,
        "rotation": 3,
        "behindText": true
      }
    ],
    "ipodTexture": "/images/ipod-texture-rusty.jpeg",
    "ipodFont": "system",
    "macPattern": "",
    "macPatternColor": "#a37710",
    "wordArtTitleStyle": "style-four",
    "phoneHomeDock": [
      "a7",
      "a0l",
      "a0x"
    ],
    "phoneHomeShowDock": true,
    "phoneHomeDockTranslucent": true,
    "phoneHomeVariant": "windows-95",
    "zineBadgeText": "NEW!",
    "zineTitleSize": 1,
    "zineShowDoodles": true,
    "artifactMarqueeText": "LINKS_DATABASE /// ACCESS_GRANTED >>> CONNECT_NOW /// NET_RUNNER",
    "artifactHeaderTopLeft": "USER.ID_99",
    "artifactHeaderTopCenter": "[ONLINE]",
    "artifactHeaderTopRight": "",
    "artifactHeaderBottomLeft": "DIGITAL // PHY",
    "artifactHeaderBottomCenter": "///",
    "artifactHeaderBottomRight": "SYS_ADMIN",
    "artifactShowHeaderMeta": true,
    "artifactHeroOverlay": true,
    "artifactHeroMediaType": "image",
    "artifactHeroImageUrl": "",
    "artifactHeroVideoUrl": "",
    "artifactHeroPositionX": 50,
    "artifactHeroPositionY": 50,
    "scatterMode": false,
    "visitorDrag": false
  },
  "profile": {
    "displayName": null,
    "bio": null,
    "avatarUrl": null,
    "avatarFeather": 0,
    "avatarSize": 80,
    "showAvatar": true,
    "showTitle": true,
    "titleSize": "small",
    "showSocialIcons": true,
    "showLogo": false,
    "logoUrl": null,
    "logoScale": 100,
    "profileLayout": "classic",
    "headerTextColor": "oklch(0 0 0)",
    "socialIconColor": "#000000",
    "socialIcons": []
  },
  "mediaAssets": [],
  "id": "phone-home-mclovins-iphone",
  "name": "MCLOVINS IPHONE",
  "description": "MCLOVINS IPHONE template",
  "thumbnailPath": "/templates/phone-home-mclovins-iphone/thumbnail.jpg"
} as const satisfies TemplateDefinition
