// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const phoneHomeWindowsPhone: TemplateDefinition = {
  "themeId": "phone-home",
  "cards": [
    {
      "card_type": "hero",
      "title": "LISTEN",
      "description": null,
      "url": null,
      "content": {
        "iconName": "Music",
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/my-computer.png",
        "showButton": false,
        "wordArtStyle": "style-four",
        "transparentBackground": false
      },
      "size": "small",
      "position": "center",
      "sortKey": "a1",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": "VIDEOS",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/folder.png",
        "showButton": false,
        "wordArtStyle": "style-seven",
        "transparentBackground": false
      },
      "size": "small",
      "position": "center",
      "sortKey": "a2",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "TOUR DATES",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "appIconUrl": "/icons/8bit/sound.png",
        "wordArtStyle": "style-twentyone",
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a6",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "MERCH",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "appIconUrl": "/icons/8bit/calculator.png",
        "wordArtStyle": "style-fourteen",
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a7",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "YOUTUBE",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "appIconUrl": "/icons/8bit/internet-explorer.png",
        "wordArtStyle": "style-three",
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a8",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "INSTAGRAM",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "appIconUrl": "/icons/8bit/my-documents.png",
        "wordArtStyle": "style-seventeen",
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a8V",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "WEBISTE",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "appIconUrl": "/icons/8bit/notepad.png",
        "wordArtStyle": "style-one",
        "phoneHomeLayout": {
          "col": 2,
          "row": 1,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a8l",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "DEMOS",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "appIconUrl": "/icons/8bit/media-player.png",
        "wordArtStyle": "style-one",
        "phoneHomeLayout": {
          "col": 2,
          "row": 1,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a8t",
      "is_visible": true
    },
    {
      "card_type": "music",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "title": "2008 Toyota Corolla",
        "embedUrl": "https://open.spotify.com/track/06ATooCLq2lm8tgFGE7scT?si=21e73184858148d7",
        "platform": "spotify",
        "embeddable": true,
        "thumbnailUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02092cecf16e143d56e7c2080e",
        "embedIframeUrl": "https://open.spotify.com/embed/track/06ATooCLq2lm8tgFGE7scT?si=21e73184858148d7&theme=0",
        "phoneHomeLayout": {
          "col": 0,
          "row": 2,
          "page": 0,
          "width": 4,
          "height": 1
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "a9",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "macLinks": [
          {
            "url": "https://open.spotify.com/album/",
            "title": "LISTEN"
          },
          {
            "url": "https://bandsintown.com/",
            "title": "VIDEOS"
          },
          {
            "url": "https://bandsintown.com/",
            "title": "TOUR DATES"
          },
          {
            "url": "https://bandsintown.com/",
            "title": "MERCH"
          }
        ],
        "notepadStyle": "buttons",
        "macWindowStyle": "notepad"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a9",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": "LINK OR VIDEO",
      "description": null,
      "url": null,
      "content": {
        "macMode": "link",
        "macTextAlign": "left",
        "macTextColor": "#000000",
        "macWindowStyle": "small-window",
        "macCheckerColor": "#cfffcc",
        "macWindowBgColor": "#afb3ee"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a9V",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": "LINK OR VIDEO",
      "description": null,
      "url": null,
      "content": {
        "macMode": "link",
        "macTextAlign": "left",
        "macTextColor": "#000",
        "macWindowStyle": "small-window",
        "macCheckerColor": "#cfffcc",
        "macWindowBgColor": "#afb3ee"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a9l",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "calcMessage": "custom message ",
        "macWindowStyle": "calculator"
      },
      "size": "big",
      "position": "left",
      "sortKey": "aA",
      "is_visible": false
    },
    {
      "card_type": "gallery",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "images": [
          {
            "id": "b04ce209-69a5-45fc-88cf-6fa1fa213579",
            "alt": "_ (22)",
            "url": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/8d1a998c-e541-4893-9ef1-3a95989595ce/e5807174-45a5-40aa-a774-66810313f03b.jpeg",
            "storagePath": "8d1a998c-e541-4893-9ef1-3a95989595ce/e5807174-45a5-40aa-a774-66810313f03b.jpeg"
          }
        ],
        "galleryStyle": "carousel",
        "phoneHomeLayout": {
          "col": 0,
          "row": 3,
          "page": 0,
          "width": 4,
          "height": 2
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "aA",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "macWindowStyle": "map"
      },
      "size": "big",
      "position": "left",
      "sortKey": "aB",
      "is_visible": false
    },
    {
      "card_type": "audio",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "tracks": [
          {
            "id": "8b5b2ab8-827c-4f60-90ec-9fa80fb70587",
            "title": "LEASE by Takeshi Abo but slightly bitcrushed for nostalgia",
            "artist": "",
            "audioUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-audio/05750469-143e-4f39-a705-3484f0beb973/8b5b2ab8-827c-4f60-90ec-9fa80fb70587.mp3",
            "duration": 103.340417
          }
        ],
        "looping": false,
        "autoplay": false,
        "reverbConfig": {
          "mix": 0.3,
          "damp": 0.5,
          "width": 0.8,
          "enabled": false,
          "roomSize": 0.5,
          "predelayMs": 20
        },
        "showWaveform": true,
        "blinkieColors": {
          "text": "#d8dec8",
          "buttons": "#b89048",
          "innerBox": "#8a9868",
          "outerBox": "#252818",
          "playerBox": "#607040"
        },
        "phoneHomeLayout": {
          "col": 0,
          "row": 2,
          "page": 1,
          "width": 1,
          "height": 1
        },
        "blinkieBoxBackgrounds": {
          "cardBgUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/05750469-143e-4f39-a705-3484f0beb973/4d81001b-9434-4c40-903e-600dec991142.jpg",
          "cardOuterDim": 56,
          "cardBgStoragePath": "05750469-143e-4f39-a705-3484f0beb973/4d81001b-9434-4c40-903e-600dec991142.jpg"
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "aB",
      "is_visible": true
    },
    {
      "card_type": "gallery",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "images": [
          {
            "id": "b58a2115-9fbf-463d-b998-07c584ca0f6f",
            "alt": "2000s vibes background",
            "url": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/7b27a17f-031e-4bcf-917d-d8fa8d935d8c/75e35c23-4da0-4fd9-b772-8fa9774a1c82.jpeg",
            "storagePath": "7b27a17f-031e-4bcf-917d-d8fa8d935d8c/75e35c23-4da0-4fd9-b772-8fa9774a1c82.jpeg"
          }
        ],
        "galleryStyle": "carousel",
        "phoneHomeLayout": {
          "col": 0,
          "row": 0,
          "page": 1,
          "width": 4,
          "height": 2
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "aC",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "albumArtUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/9b437c15-d956-4b88-9b2e-3c1681fec566/85a9c56a-9544-41db-b943-26d16c0610cb.jpg",
        "showCountdown": true,
        "macWindowStyle": "presave",
        "presaveBgColor": "#F2FFA4",
        "preSaveButtonText": "Pre-save",
        "afterCountdownText": "OUT NOW",
        "albumArtStoragePath": "9b437c15-d956-4b88-9b2e-3c1681fec566/85a9c56a-9544-41db-b943-26d16c0610cb.jpg",
        "afterCountdownAction": "custom"
      },
      "size": "big",
      "position": "left",
      "sortKey": "aD",
      "is_visible": false
    }
  ],
  "theme": {
    "themeId": "phone-home",
    "paletteId": "phone-dark",
    "colors": {
      "link": "oklch(0.62 0.22 250)",
      "text": "oklch(1 0 0)",
      "accent": "oklch(0.62 0.22 250)",
      "border": "oklch(0.40 0 0 / 0.3)",
      "cardBg": "oklch(0.25 0 0 / 0.6)",
      "background": "oklch(0.13 0 0)"
    },
    "fonts": {
      "body": "var(--font-geist-sans)",
      "heading": "var(--font-geist-sans)",
      "bodySize": 0.85,
      "headingSize": 1,
      "headingWeight": "normal"
    },
    "style": {
      "borderRadius": 16,
      "blurIntensity": 0,
      "shadowEnabled": false
    },
    "background": {
      "type": "image",
      "value": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/36eb6d57-7a64-458a-aafa-16e076ead485/backgrounds/1771591832843.jpeg",
      "dimOverlay": false,
      "topBarColor": "#3d61a8",
      "dimIntensity": 25
    },
    "cardTypeFontSizes": {
      "hero": 0.8,
      "square": 1,
      "horizontal": 1,
      "link": 1.2,
      "mini": 1,
      "text": 1,
      "gallery": 1,
      "video": 1
    },
    "centerCards": false,
    "vcrCenterContent": false,
    "receiptPrice": "PRICELESS",
    "receiptStickers": [],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": false,
    "ipodStickers": [],
    "ipodTexture": "/images/ipod-texture-scratched.jpeg",
    "ipodFont": "system",
    "macPattern": "/images/mac-patterns/pattern-1.png",
    "macPatternColor": "#7e350d",
    "wordArtTitleStyle": "style-three",
    "phoneHomeDock": [],
    "phoneHomeShowDock": true,
    "phoneHomeVariant": "default",
    "zineBadgeText": "NEW!",
    "zineTitleSize": 1,
    "zineShowDoodles": true,
    "artifactMarqueeText": "LINKS_DATABASE /// ACCESS_GRANTED >>> CONNECT_NOW /// NET_RUNNER",
    "artifactHeaderTopLeft": "USER.ID_99",
    "artifactHeaderTopCenter": "[ONLINE]",
    "artifactHeaderTopRight": "",
    "artifactHeaderBottomLeft": "DIGITAL // PHY",
    "artifactHeaderBottomCenter": "///",
    "artifactHeaderBottomRight": "SYS_ADMIN",
    "artifactShowHeaderMeta": true,
    "artifactHeroOverlay": true,
    "artifactHeroMediaType": "image",
    "artifactHeroImageUrl": "",
    "artifactHeroVideoUrl": "",
    "artifactHeroPositionX": 50,
    "artifactHeroPositionY": 50,
    "scatterMode": false,
    "visitorDrag": false
  },
  "profile": {
    "displayName": "YOUR NAME",
    "bio": null,
    "avatarUrl": null,
    "avatarFeather": 0,
    "showAvatar": true,
    "showTitle": true,
    "titleSize": "small",
    "showSocialIcons": true,
    "showLogo": false,
    "logoUrl": null,
    "logoScale": 100,
    "profileLayout": "classic",
    "headerTextColor": "#ffffff",
    "socialIconColor": "#ffffff",
    "socialIcons": [
      {
        "id": "86ec3c07-a25a-4aaf-b063-98ae75cf1fa8",
        "url": "",
        "sortKey": "a1",
        "platform": "instagram"
      },
      {
        "id": "144c3a93-9040-471f-86d9-cacda54921ff",
        "url": "",
        "sortKey": "a2",
        "platform": "spotify"
      },
      {
        "id": "8d4ad2df-d302-4e46-a9f6-a4f19633c261",
        "url": "",
        "sortKey": "a3",
        "platform": "tiktok"
      }
    ]
  },
  "mediaAssets": [],
  "id": "phone-home-windows-phone",
  "name": "WINDOWS PHONE",
  "description": "WINDOWS PHONE template",
  "thumbnailPath": "/templates/phone-home-windows-phone/thumbnail.jpg"
} as const satisfies TemplateDefinition
