// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const macOsWhiteLight: TemplateDefinition = {
  "themeId": "mac-os",
  "cards": [
    {
      "card_type": "square",
      "title": "LISTEN",
      "description": null,
      "url": "https://open.spotify.com/album/",
      "content": {
        "iconName": "Music",
        "imageUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/2ab60e0b-778c-4cfe-a881-6a8f194f6600/d1531754-b6e5-46ec-88e9-c64ef7853a82.gif",
        "textAlign": "center",
        "showButton": false,
        "transparentBackground": true
      },
      "size": "small",
      "position": "center",
      "sortKey": "a1",
      "is_visible": true
    },
    {
      "card_type": "square",
      "title": "VIDEOS",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "imageUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/4371da8e-aef3-4a3c-b6c2-bd714dfb5a3c/aa5d7e0a-3849-4f23-a5c1-bd2d2fb6f8c1.gif",
        "textAlign": "center",
        "showButton": false,
        "transparentBackground": true
      },
      "size": "small",
      "position": "center",
      "sortKey": "a2",
      "is_visible": true
    },
    {
      "card_type": "gallery",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "images": [
          {
            "id": "f18609c3-4ff6-4a3f-be15-7bbb0a9d781a",
            "alt": "Music",
            "url": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/c1398520-b8e8-4aaa-b1b6-ee25da524ac6/fca67213-8ee4-4efc-a47e-0b5c306452d0.gif",
            "caption": "LINK",
            "storagePath": "c1398520-b8e8-4aaa-b1b6-ee25da524ac6/fca67213-8ee4-4efc-a47e-0b5c306452d0.gif"
          },
          {
            "id": "dfe25d5a-2c91-4915-84ec-f47f21b7031c",
            "alt": "Music",
            "url": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/c1398520-b8e8-4aaa-b1b6-ee25da524ac6/6c2ab00c-a97c-4a34-863f-8ba7bfd016a2.gif",
            "caption": "LINK",
            "storagePath": "c1398520-b8e8-4aaa-b1b6-ee25da524ac6/6c2ab00c-a97c-4a34-863f-8ba7bfd016a2.gif"
          }
        ],
        "spacing": 0.5,
        "borderRadius": 0.5,
        "captionColor": "#000000",
        "galleryStyle": "circular",
        "transparentBackground": true
      },
      "size": "big",
      "position": "left",
      "sortKey": "a3",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "TOUR DATES",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "textColor": "#000000",
        "transparentBackground": true
      },
      "size": "big",
      "position": "center",
      "sortKey": "a6",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "MERCH",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "textColor": "#000000",
        "transparentBackground": true
      },
      "size": "big",
      "position": "center",
      "sortKey": "a7",
      "is_visible": true
    }
  ],
  "theme": {
    "themeId": "mac-os",
    "paletteId": null,
    "colors": {
      "background": "#ffffff",
      "cardBg": "#ebd0d0",
      "text": "#ffffff",
      "accent": "oklch(0.65 0.15 250)",
      "border": "#2215b0",
      "link": "oklch(0.35 0.12 250)",
      "titleBarLine": "#d50000"
    },
    "fonts": {
      "heading": "var(--font-chicago)",
      "body": "var(--font-chicago)",
      "headingSize": 1,
      "bodySize": 1,
      "headingWeight": "bold"
    },
    "style": {
      "borderRadius": 10,
      "shadowEnabled": true,
      "blurIntensity": 0
    },
    "background": {
      "type": "solid",
      "value": "#ffffff",
      "topBarColor": "#071081"
    },
    "cardTypeFontSizes": {
      "hero": 0.8,
      "square": 1,
      "horizontal": 1,
      "link": 1.2,
      "mini": 1,
      "text": 1,
      "gallery": 1,
      "video": 1
    },
    "centerCards": true,
    "vcrCenterContent": false,
    "receiptPrice": "PRICELESS",
    "receiptStickers": [],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": false,
    "ipodStickers": [],
    "ipodTexture": "/images/metal-texture.jpeg",
    "ipodFont": "system",
    "macPattern": "",
    "macPatternColor": "#c0c0c0",
    "wordArtTitleStyle": "style-eleven",
    "phoneHomeDock": [],
    "phoneHomeShowDock": true,
    "phoneHomeDockTranslucent": true,
    "phoneHomeVariant": "default",
    "zineBadgeText": "NEW!",
    "zineTitleSize": 1,
    "zineShowDoodles": true,
    "artifactMarqueeText": "LINKS_DATABASE /// ACCESS_GRANTED >>> CONNECT_NOW /// NET_RUNNER",
    "artifactHeaderTopLeft": "USER.ID_99",
    "artifactHeaderTopCenter": "[ONLINE]",
    "artifactHeaderTopRight": "",
    "artifactHeaderBottomLeft": "DIGITAL // PHY",
    "artifactHeaderBottomCenter": "///",
    "artifactHeaderBottomRight": "SYS_ADMIN",
    "artifactShowHeaderMeta": true,
    "artifactHeroOverlay": true,
    "artifactHeroMediaType": "image",
    "artifactHeroImageUrl": "",
    "artifactHeroVideoUrl": "",
    "artifactHeroPositionX": 50,
    "artifactHeroPositionY": 50,
    "scatterMode": false,
    "visitorDrag": false
  },
  "profile": {
    "displayName": "",
    "bio": null,
    "avatarUrl": null,
    "avatarFeather": 0,
    "showAvatar": false,
    "showTitle": false,
    "titleSize": "small",
    "showSocialIcons": true,
    "showLogo": false,
    "logoUrl": null,
    "logoScale": 100,
    "profileLayout": "classic",
    "headerTextColor": "#a60000",
    "socialIconColor": "#a30000",
    "socialIcons": []
  },
  "mediaAssets": [],
  "id": "mac-os-white-light",
  "name": "WHITE LIGHT",
  "description": "WHITE LIGHT template",
  "thumbnailPath": "/templates/mac-os-white-light/thumbnail.jpg"
} as const satisfies TemplateDefinition
