// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const instagramReelsCards: TemplateDefinition = {
  "themeId": "instagram-reels",
  "cards": [
    {
      "card_type": "social-icons",
      "title": null,
      "description": null,
      "url": null,
      "content": {},
      "size": "big",
      "position": "center",
      "sortKey": "Zz",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": "YOUR NAME",
      "description": "Composer · Producer",
      "url": null,
      "content": {
        "buttonText": "Explore",
        "showButton": true,
        "buttonStyle": "primary"
      },
      "size": "big",
      "position": "center",
      "sortKey": "a0",
      "is_visible": true
    },
    {
      "card_type": "square",
      "title": "Latest Release",
      "description": "Out now",
      "url": "https://open.spotify.com/",
      "content": {},
      "size": "small",
      "position": "left",
      "sortKey": "a1",
      "is_visible": true
    },
    {
      "card_type": "square",
      "title": "Visuals",
      "description": "Watch",
      "url": "https://youtube.com/",
      "content": {},
      "size": "small",
      "position": "right",
      "sortKey": "a2",
      "is_visible": true
    },
    {
      "card_type": "gallery",
      "title": "Recents",
      "description": null,
      "url": null,
      "content": {
        "images": [],
        "displayMode": "carousel"
      },
      "size": "big",
      "position": "center",
      "sortKey": "a3",
      "is_visible": true
    },
    {
      "card_type": "video",
      "title": "Live Session",
      "description": null,
      "url": null,
      "content": {
        "platform": "youtube",
        "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
      },
      "size": "big",
      "position": "center",
      "sortKey": "a4",
      "is_visible": true
    },
    {
      "card_type": "music",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "embedUrl": "https://open.spotify.com/track/6IRVovQruBNy9PIqOnAxFf",
        "platform": "spotify",
        "embeddable": true,
        "embedHeight": 152,
        "embedIframeUrl": "https://open.spotify.com/embed/track/6IRVovQruBNy9PIqOnAxFf"
      },
      "size": "big",
      "position": "center",
      "sortKey": "a5",
      "is_visible": true
    },
    {
      "card_type": "horizontal",
      "title": "Upcoming Shows",
      "description": "Tickets & info",
      "url": "https://example.com/shows",
      "content": {
        "iconName": "Calendar"
      },
      "size": "big",
      "position": "center",
      "sortKey": "a6",
      "is_visible": true
    }
  ],
  "theme": {
    "themeId": "instagram-reels",
    "paletteId": null,
    "colors": {
      "background": "oklch(0 0 0)",
      "cardBg": "oklch(0 0 0)",
      "text": "oklch(0.95 0 0)",
      "accent": "#000000",
      "border": "oklch(0.95 0 0)",
      "link": "oklch(0.95 0 0)"
    },
    "fonts": {
      "heading": "var(--font-bebas-neue)",
      "body": "var(--font-sora)",
      "headingSize": 1.3,
      "bodySize": 1,
      "headingWeight": "bold"
    },
    "style": {
      "borderRadius": 16,
      "shadowEnabled": false,
      "blurIntensity": 0
    },
    "background": {
      "type": "solid",
      "value": "oklch(0 0 0)"
    },
    "cardTypeFontSizes": {
      "hero": 1.2,
      "square": 1.1,
      "horizontal": 1,
      "link": 1,
      "mini": 1,
      "text": 1,
      "gallery": 1,
      "video": 1
    },
    "centerCards": false,
    "vcrCenterContent": false,
    "receiptPrice": "PRICELESS",
    "receiptStickers": [],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": false,
    "ipodStickers": [],
    "ipodTexture": "/images/metal-texture.jpeg",
    "ipodFont": "system",
    "macPattern": "",
    "macPatternColor": "#c0c0c0",
    "wordArtTitleStyle": "style-eleven",
    "lanyardActiveView": 0,
    "classifiedStampText": "SECRET",
    "classifiedDeptText": "War Department",
    "classifiedCenterText": "Classified Message Center",
    "classifiedMessageText": "Incoming Message",
    "phoneHomeDock": [],
    "phoneHomeShowDock": true,
    "phoneHomeVariant": "default",
    "zineBadgeText": "NEW!",
    "zineTitleSize": 1,
    "zineShowDoodles": true,
    "artifactMarqueeText": "LINKS_DATABASE /// ACCESS_GRANTED >>> CONNECT_NOW /// NET_RUNNER",
    "artifactHeaderTopLeft": "USER.ID_99",
    "artifactHeaderTopCenter": "[ONLINE]",
    "artifactHeaderTopRight": "",
    "artifactHeaderBottomLeft": "DIGITAL // PHY",
    "artifactHeaderBottomCenter": "///",
    "artifactHeaderBottomRight": "SYS_ADMIN",
    "artifactShowHeaderMeta": true,
    "artifactHeroOverlay": true,
    "artifactHeroMediaType": "image",
    "artifactHeroImageUrl": "",
    "artifactHeroVideoUrl": "",
    "artifactHeroPositionX": 50,
    "artifactHeroPositionY": 50,
    "scatterMode": false,
    "visitorDrag": false
  },
  "profile": {
    "displayName": "YOUR NAME",
    "bio": "Composer · Producer",
    "avatarUrl": null,
    "avatarFeather": 0,
    "showAvatar": true,
    "showTitle": true,
    "titleSize": "large",
    "showSocialIcons": true,
    "showLogo": false,
    "logoUrl": null,
    "logoScale": 100,
    "profileLayout": "classic",
    "headerTextColor": "oklch(0.95 0 0)",
    "socialIconColor": "oklch(0.95 0 0)",
    "socialIcons": [
      {
        "id": "tpl-1",
        "platform": "instagram",
        "url": "https://instagram.com/",
        "sortKey": "a0"
      },
      {
        "id": "tpl-2",
        "platform": "tiktok",
        "url": "https://tiktok.com/",
        "sortKey": "a1"
      },
      {
        "id": "tpl-3",
        "platform": "spotify",
        "url": "https://open.spotify.com/",
        "sortKey": "a2"
      },
      {
        "id": "tpl-4",
        "platform": "youtube",
        "url": "https://youtube.com/",
        "sortKey": "a3"
      },
      {
        "id": "tpl-5",
        "platform": "soundcloud",
        "url": "https://soundcloud.com/",
        "sortKey": "a4"
      }
    ]
  },
  "mediaAssets": [],
  "id": "instagram-reels-cards",
  "name": "CARDS!",
  "description": "CARDS! template",
  "thumbnailPath": "/templates/instagram-reels-cards/thumbnail.jpg"
} as const satisfies TemplateDefinition
