// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const instagramReelsCdeez: TemplateDefinition = {
  "themeId": "instagram-reels",
  "cards": [
    {
      "card_type": "social-icons",
      "title": null,
      "description": null,
      "url": null,
      "content": {},
      "size": "big",
      "position": "left",
      "sortKey": "a0",
      "is_visible": true
    },
    {
      "card_type": "gallery",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "images": [
          {
            "id": "f18609c3-4ff6-4a3f-be15-7bbb0a9d781a",
            "alt": "Music",
            "url": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/c1398520-b8e8-4aaa-b1b6-ee25da524ac6/fca67213-8ee4-4efc-a47e-0b5c306452d0.gif",
            "storagePath": "c1398520-b8e8-4aaa-b1b6-ee25da524ac6/fca67213-8ee4-4efc-a47e-0b5c306452d0.gif",
            "caption": "LINK"
          },
          {
            "id": "dfe25d5a-2c91-4915-84ec-f47f21b7031c",
            "alt": "Music",
            "url": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/c1398520-b8e8-4aaa-b1b6-ee25da524ac6/6c2ab00c-a97c-4a34-863f-8ba7bfd016a2.gif",
            "storagePath": "c1398520-b8e8-4aaa-b1b6-ee25da524ac6/6c2ab00c-a97c-4a34-863f-8ba7bfd016a2.gif",
            "caption": "LINK"
          }
        ],
        "spacing": 0.5,
        "borderRadius": 0.5,
        "galleryStyle": "circular",
        "transparentBackground": true,
        "captionColor": "#000000"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a0V",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": "NEW SONG",
      "description": null,
      "url": "https://open.spotify.com/album/",
      "content": {
        "iconName": "Music",
        "textAlign": "center",
        "showButton": false
      },
      "size": "small",
      "position": "center",
      "sortKey": "a1",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": "VIDEOS",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "textAlign": "center",
        "showButton": false
      },
      "size": "small",
      "position": "center",
      "sortKey": "a2",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "TOUR DATES",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin"
      },
      "size": "big",
      "position": "center",
      "sortKey": "a3",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "MERCH",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin"
      },
      "size": "big",
      "position": "center",
      "sortKey": "a4",
      "is_visible": true
    },
    {
      "card_type": "square",
      "title": "IMAGE",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "verticalAlign": "bottom"
      },
      "size": "small",
      "position": "left",
      "sortKey": "a6G",
      "is_visible": true
    },
    {
      "card_type": "square",
      "title": "IMAGE",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "verticalAlign": "bottom"
      },
      "size": "small",
      "position": "left",
      "sortKey": "a6V",
      "is_visible": true
    }
  ],
  "theme": {
    "themeId": "instagram-reels",
    "paletteId": null,
    "colors": {
      "link": "#a70000",
      "text": "#ffffff",
      "accent": "#a70000",
      "border": "#000000",
      "cardBg": "#240f06",
      "background": "#ffffff"
    },
    "fonts": {
      "body": "var(--font-chikarego)",
      "heading": "var(--font-hypermarket)",
      "bodySize": 1,
      "headingSize": 1.1,
      "headingWeight": "bold"
    },
    "style": {
      "borderRadius": 10,
      "blurIntensity": 0,
      "shadowEnabled": false
    },
    "background": {
      "type": "solid",
      "value": "#ffffff"
    },
    "cardTypeFontSizes": {
      "hero": 0.8,
      "square": 1,
      "horizontal": 1,
      "link": 1.2,
      "mini": 1,
      "text": 1,
      "gallery": 1,
      "video": 1
    },
    "centerCards": false,
    "vcrCenterContent": false,
    "receiptPrice": "PRICELESS",
    "receiptStickers": [],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": false,
    "ipodStickers": [],
    "ipodTexture": "/images/metal-texture.jpeg",
    "ipodFont": "system",
    "macPattern": "",
    "macPatternColor": "#c0c0c0",
    "wordArtTitleStyle": "style-eleven",
    "lanyardActiveView": 0,
    "classifiedStampText": "SECRET",
    "classifiedDeptText": "War Department",
    "classifiedCenterText": "Classified Message Center",
    "classifiedMessageText": "Incoming Message",
    "phoneHomeDock": [],
    "phoneHomeShowDock": true,
    "phoneHomeVariant": "default",
    "zineBadgeText": "NEW!",
    "zineTitleSize": 1,
    "zineShowDoodles": true,
    "artifactMarqueeText": "LINKS_DATABASE /// ACCESS_GRANTED >>> CONNECT_NOW /// NET_RUNNER",
    "artifactHeaderTopLeft": "USER.ID_99",
    "artifactHeaderTopCenter": "[ONLINE]",
    "artifactHeaderTopRight": "",
    "artifactHeaderBottomLeft": "DIGITAL // PHY",
    "artifactHeaderBottomCenter": "///",
    "artifactHeaderBottomRight": "SYS_ADMIN",
    "artifactShowHeaderMeta": true,
    "artifactHeroOverlay": true,
    "artifactHeroMediaType": "image",
    "artifactHeroImageUrl": "",
    "artifactHeroVideoUrl": "",
    "artifactHeroPositionX": 50,
    "artifactHeroPositionY": 50,
    "scatterMode": false,
    "visitorDrag": false
  },
  "profile": {
    "displayName": "YOUR NAME",
    "bio": null,
    "avatarUrl": null,
    "avatarFeather": 0,
    "showAvatar": true,
    "showTitle": true,
    "titleSize": "small",
    "showSocialIcons": true,
    "showLogo": false,
    "logoUrl": null,
    "logoScale": 100,
    "profileLayout": "classic",
    "headerTextColor": "#000000",
    "socialIconColor": "#000000",
    "socialIcons": [
      {
        "id": "d720a696-fcb5-4ec2-aa37-a5ca2e749027",
        "url": "",
        "sortKey": "a0",
        "platform": "twitter"
      },
      {
        "id": "86ec3c07-a25a-4aaf-b063-98ae75cf1fa8",
        "url": "",
        "sortKey": "a1",
        "platform": "instagram"
      },
      {
        "id": "144c3a93-9040-471f-86d9-cacda54921ff",
        "url": "",
        "sortKey": "a2",
        "platform": "spotify"
      },
      {
        "id": "8d4ad2df-d302-4e46-a9f6-a4f19633c261",
        "url": "",
        "sortKey": "a3",
        "platform": "tiktok"
      }
    ]
  },
  "mediaAssets": [],
  "id": "instagram-reels-cdeez",
  "name": "CDEEZ",
  "description": "CDEEZ template",
  "thumbnailPath": "/templates/instagram-reels-cdeez/thumbnail.jpg"
} as const satisfies TemplateDefinition
