// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const instagramReelsYellowBrown: TemplateDefinition = {
  "themeId": "instagram-reels",
  "cards": [
    {
      "card_type": "social-icons",
      "title": null,
      "description": null,
      "url": null,
      "content": {},
      "size": "big",
      "position": "left",
      "sortKey": "Zy",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "NEW SONG",
      "description": null,
      "url": "https://open.spotify.com/album/",
      "content": {
        "iconName": "Music",
        "textColor": "#ffbb00"
      },
      "size": "big",
      "position": "center",
      "sortKey": "Zz",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "VIDEOS",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "textColor": "#ffbb00"
      },
      "size": "big",
      "position": "center",
      "sortKey": "a0",
      "is_visible": true
    },
    {
      "card_type": "square",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "verticalAlign": "bottom"
      },
      "size": "small",
      "position": "left",
      "sortKey": "a1V",
      "is_visible": true
    },
    {
      "card_type": "square",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "verticalAlign": "bottom"
      },
      "size": "small",
      "position": "left",
      "sortKey": "a1l",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "TOUR DATES",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "textColor": "#ffbb00"
      },
      "size": "big",
      "position": "center",
      "sortKey": "a3",
      "is_visible": true
    }
  ],
  "theme": {
    "themeId": "instagram-reels",
    "paletteId": null,
    "colors": {
      "link": "#ff0000",
      "text": "#fff8e4",
      "accent": "oklch(0.65 0.28 25)",
      "border": "#ffa800",
      "cardBg": "#431e0c",
      "background": "#ffa800"
    },
    "fonts": {
      "body": "var(--font-chikarego)",
      "heading": "var(--font-aux-mono)",
      "bodySize": 1,
      "headingSize": 1.1,
      "headingWeight": "bold"
    },
    "style": {
      "borderRadius": 0,
      "blurIntensity": 0,
      "shadowEnabled": false
    },
    "background": {
      "type": "solid",
      "value": "#ffa800",
      "dimOverlay": false,
      "noiseOverlay": false
    },
    "cardTypeFontSizes": {
      "hero": 1,
      "square": 1,
      "horizontal": 1,
      "link": 1,
      "mini": 1,
      "text": 1,
      "gallery": 1,
      "video": 1
    },
    "centerCards": false,
    "vcrCenterContent": false,
    "receiptPrice": "PRICELESS",
    "receiptStickers": [],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": false,
    "ipodStickers": [],
    "ipodTexture": "/images/metal-texture.jpeg",
    "ipodFont": "system",
    "macPattern": "",
    "macPatternColor": "#c0c0c0",
    "wordArtTitleStyle": "style-eleven",
    "lanyardActiveView": 0,
    "classifiedStampText": "SECRET",
    "classifiedDeptText": "War Department",
    "classifiedCenterText": "Classified Message Center",
    "classifiedMessageText": "Incoming Message",
    "phoneHomeDock": [],
    "phoneHomeShowDock": true,
    "phoneHomeVariant": "default",
    "zineBadgeText": "NEW!",
    "zineTitleSize": 1,
    "zineShowDoodles": true,
    "artifactMarqueeText": "LINKS_DATABASE /// ACCESS_GRANTED >>> CONNECT_NOW /// NET_RUNNER",
    "artifactHeaderTopLeft": "USER.ID_99",
    "artifactHeaderTopCenter": "[ONLINE]",
    "artifactHeaderTopRight": "",
    "artifactHeaderBottomLeft": "DIGITAL // PHY",
    "artifactHeaderBottomCenter": "///",
    "artifactHeaderBottomRight": "SYS_ADMIN",
    "artifactShowHeaderMeta": true,
    "artifactHeroOverlay": true,
    "artifactHeroMediaType": "image",
    "artifactHeroImageUrl": "",
    "artifactHeroVideoUrl": "",
    "artifactHeroPositionX": 50,
    "artifactHeroPositionY": 50,
    "scatterMode": false,
    "visitorDrag": false
  },
  "profile": {
    "displayName": "YOUR NAME",
    "bio": null,
    "avatarUrl": null,
    "avatarFeather": 0,
    "showAvatar": true,
    "showTitle": true,
    "titleSize": "small",
    "showSocialIcons": true,
    "showLogo": false,
    "logoUrl": null,
    "logoScale": 100,
    "profileLayout": "classic",
    "headerTextColor": "#723c1b",
    "socialIconColor": "#723c1b",
    "socialIcons": [
      {
        "id": "d720a696-fcb5-4ec2-aa37-a5ca2e749027",
        "url": "",
        "sortKey": "a0",
        "platform": "twitter"
      },
      {
        "id": "86ec3c07-a25a-4aaf-b063-98ae75cf1fa8",
        "url": "",
        "sortKey": "a1",
        "platform": "instagram"
      },
      {
        "id": "144c3a93-9040-471f-86d9-cacda54921ff",
        "url": "",
        "sortKey": "a2",
        "platform": "spotify"
      },
      {
        "id": "8d4ad2df-d302-4e46-a9f6-a4f19633c261",
        "url": "",
        "sortKey": "a3",
        "platform": "tiktok"
      }
    ]
  },
  "mediaAssets": [],
  "id": "instagram-reels-yellow-brown",
  "name": "YELLOW + BROWN",
  "description": "YELLOW + BROWN template",
  "thumbnailPath": "/templates/instagram-reels-yellow-brown/thumbnail.jpg"
} as const satisfies TemplateDefinition
