// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const macintosh84Tosh: TemplateDefinition = {
  "themeId": "macintosh",
  "cards": [
    {
      "card_type": "audio",
      "title": "PLAYER",
      "description": null,
      "url": null,
      "content": {
        "tracks": [],
        "looping": false,
        "reverbConfig": {
          "mix": 0.3,
          "damp": 0.5,
          "width": 0.8,
          "enabled": false,
          "roomSize": 0.5,
          "predelayMs": 20
        },
        "showWaveform": true,
        "_hiddenForMac": true
      },
      "size": "big",
      "position": "left",
      "sortKey": "a0",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": "LISTEN",
      "description": null,
      "url": "https://open.spotify.com/album/",
      "content": {
        "iconName": "Music",
        "textAlign": "center",
        "showButton": false,
        "_hiddenForMac": true,
        "transparentBackground": false
      },
      "size": "small",
      "position": "center",
      "sortKey": "a1",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": "VIDEOS",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "textAlign": "center",
        "showButton": false,
        "_hiddenForMac": true,
        "transparentBackground": false
      },
      "size": "small",
      "position": "center",
      "sortKey": "a2",
      "is_visible": false
    },
    {
      "card_type": "link",
      "title": "TOUR DATES",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "_hiddenForMac": true,
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a6",
      "is_visible": false
    },
    {
      "card_type": "link",
      "title": "MERCH",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "_hiddenForMac": true,
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a7",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "macLinks": [
          {
            "url": "https://open.spotify.com/album/",
            "title": "LISTEN"
          },
          {
            "url": "https://bandsintown.com/",
            "title": "VIDEOS"
          },
          {
            "url": "https://bandsintown.com/",
            "title": "TOUR DATES"
          },
          {
            "url": "https://bandsintown.com/",
            "title": "MERCH"
          }
        ],
        "notepadStyle": "buttons",
        "macWindowStyle": "notepad"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a9",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": "LINK OR VIDEO",
      "description": null,
      "url": null,
      "content": {
        "macMode": "link",
        "macTextAlign": "left",
        "macTextColor": "#000",
        "macWindowStyle": "small-window",
        "macCheckerColor": "#cfffcc",
        "macWindowBgColor": "#afb3ee"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a9V",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": "LINK OR VIDEO",
      "description": null,
      "url": null,
      "content": {
        "macMode": "link",
        "macTextAlign": "left",
        "macTextColor": "#000",
        "macWindowStyle": "small-window",
        "macCheckerColor": "#cfffcc",
        "macWindowBgColor": "#afb3ee"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a9l",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "calcMessage": "custom message ",
        "macWindowStyle": "calculator"
      },
      "size": "big",
      "position": "left",
      "sortKey": "aA",
      "is_visible": true
    },
    {
      "card_type": "audio",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "tracks": [],
        "looping": false,
        "playerColors": {
          "elementBgColor": "#ffffff"
        },
        "reverbConfig": {
          "mix": 0.3,
          "damp": 0.5,
          "width": 0.8,
          "enabled": false,
          "roomSize": 0.5,
          "predelayMs": 20
        },
        "showWaveform": true
      },
      "size": "big",
      "position": "left",
      "sortKey": "aAV",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "macWindowStyle": "map"
      },
      "size": "big",
      "position": "left",
      "sortKey": "aB",
      "is_visible": true
    },
    {
      "card_type": "social-icons",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "aC",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textColor": "#000000",
        "albumArtUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/9b437c15-d956-4b88-9b2e-3c1681fec566/a69a3586-2452-40ea-af72-ce5c51e5fe2f.jpg",
        "showCountdown": true,
        "macWindowStyle": "presave",
        "presaveBgColor": "#F2FFA4",
        "preSaveButtonText": "Pre-save",
        "afterCountdownText": "OUT NOW",
        "albumArtStoragePath": "9b437c15-d956-4b88-9b2e-3c1681fec566/a69a3586-2452-40ea-af72-ce5c51e5fe2f.jpg",
        "afterCountdownAction": "custom"
      },
      "size": "big",
      "position": "left",
      "sortKey": "aD",
      "is_visible": true
    }
  ],
  "theme": {
    "themeId": "macintosh",
    "paletteId": "classic-gray",
    "colors": {
      "link": "#0000ff",
      "text": "#000000",
      "accent": "#ffffff",
      "border": "#000000",
      "cardBg": "#ffffff",
      "background": "#cccccc"
    },
    "fonts": {
      "body": "var(--font-courier-prime)",
      "heading": "var(--font-vt323)",
      "bodySize": 1,
      "headingSize": 1.2,
      "headingWeight": "normal"
    },
    "style": {
      "borderRadius": 0,
      "blurIntensity": 0,
      "shadowEnabled": true
    },
    "background": {
      "type": "solid",
      "value": "#cccccc"
    },
    "cardTypeFontSizes": {
      "hero": 0.8,
      "square": 1,
      "horizontal": 1,
      "link": 1.2,
      "mini": 1,
      "text": 1,
      "gallery": 1,
      "video": 1
    },
    "centerCards": false,
    "vcrCenterContent": false,
    "receiptPrice": "PRICELESS",
    "receiptStickers": [],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": false,
    "ipodStickers": [],
    "ipodTexture": "/images/ipod-texture-scratched.jpeg",
    "ipodFont": "system",
    "macPattern": "/images/mac-patterns/pattern-1.png",
    "macPatternColor": "#7e350d",
    "wordArtTitleStyle": "style-eleven",
    "phoneHomeDock": [],
    "phoneHomeShowDock": true,
    "phoneHomeVariant": "default",
    "zineBadgeText": "NEW!",
    "zineTitleSize": 1,
    "zineShowDoodles": true,
    "artifactMarqueeText": "LINKS_DATABASE /// ACCESS_GRANTED >>> CONNECT_NOW /// NET_RUNNER",
    "artifactHeaderTopLeft": "USER.ID_99",
    "artifactHeaderTopCenter": "[ONLINE]",
    "artifactHeaderTopRight": "",
    "artifactHeaderBottomLeft": "DIGITAL // PHY",
    "artifactHeaderBottomCenter": "///",
    "artifactHeaderBottomRight": "SYS_ADMIN",
    "artifactShowHeaderMeta": true,
    "artifactHeroOverlay": true,
    "artifactHeroMediaType": "image",
    "artifactHeroImageUrl": "",
    "artifactHeroVideoUrl": "",
    "artifactHeroPositionX": 50,
    "artifactHeroPositionY": 50,
    "scatterMode": false,
    "visitorDrag": false
  },
  "profile": {
    "displayName": "YOUR NAME",
    "bio": null,
    "avatarUrl": null,
    "avatarFeather": 0,
    "showAvatar": true,
    "showTitle": true,
    "titleSize": "small",
    "showSocialIcons": true,
    "showLogo": false,
    "logoUrl": null,
    "logoScale": 100,
    "profileLayout": "classic",
    "headerTextColor": "#ffffff",
    "socialIconColor": "#ffffff",
    "socialIcons": [
      {
        "id": "d720a696-fcb5-4ec2-aa37-a5ca2e749027",
        "url": "",
        "sortKey": "a0",
        "platform": "twitter"
      },
      {
        "id": "86ec3c07-a25a-4aaf-b063-98ae75cf1fa8",
        "url": "",
        "sortKey": "a1",
        "platform": "instagram"
      },
      {
        "id": "144c3a93-9040-471f-86d9-cacda54921ff",
        "url": "",
        "sortKey": "a2",
        "platform": "spotify"
      },
      {
        "id": "8d4ad2df-d302-4e46-a9f6-a4f19633c261",
        "url": "",
        "sortKey": "a3",
        "platform": "tiktok"
      }
    ]
  },
  "mediaAssets": [],
  "id": "macintosh-84-tosh",
  "name": "84' TOSH",
  "description": "84' TOSH template",
  "thumbnailPath": "/templates/macintosh-84-tosh/thumbnail.jpg"
} as const satisfies TemplateDefinition
