// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const chaoticZineOG: TemplateDefinition = {
  "themeId": "chaotic-zine",
  "cards": [
    {
      "card_type": "link",
      "title": "LISTEN",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/winamp.png",
        "wordArtStyle": "style-five",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 0,
          "row": 0,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a0",
      "is_visible": true
    },
    {
      "card_type": "square",
      "title": "WATCH",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/b435e43e-bf3c-4954-ab7e-7154997764fb/d845b11e-3879-4337-b055-6417500c09cc.png",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 3,
          "row": 0,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "small",
      "position": "left",
      "sortKey": "a1",
      "is_visible": true
    },
    {
      "card_type": "square",
      "title": "MORE",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/c2be249f-face-4178-bdb9-ed6e8df4a0b9/d18a560d-5f80-4cfa-9a8e-4047f103448e.png",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 1,
          "row": 0,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "small",
      "position": "left",
      "sortKey": "a2",
      "is_visible": true
    },
    {
      "card_type": "gallery",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "images": [
          {
            "id": "e92c6bef-bc5a-48be-85be-52be637888a4",
            "alt": "_ (22)",
            "url": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/dd2cae07-d38a-4a6d-b043-0f8a36407c2a/e01ee20c-a2ba-4f73-8ebf-d5f08ed09f73.jpg",
            "storagePath": "dd2cae07-d38a-4a6d-b043-0f8a36407c2a/e01ee20c-a2ba-4f73-8ebf-d5f08ed09f73.jpg"
          }
        ],
        "galleryStyle": "carousel",
        "phoneHomeLayout": {
          "col": 0,
          "row": 1,
          "page": 1,
          "width": 4,
          "height": 2
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a3",
      "is_visible": true
    },
    {
      "card_type": "audio",
      "title": "PLAYER",
      "description": null,
      "url": null,
      "content": {
        "tracks": [
          {
            "id": "f8bc85ad-22b8-43d5-9aef-c330698751e8",
            "title": "LEASE by Takeshi Abo but slightly bitcrushed for nostalgia",
            "artist": "",
            "audioUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-audio/cead228f-f7b6-429e-a2f3-76fc273e66c1/f8bc85ad-22b8-43d5-9aef-c330698751e8.mp3",
            "duration": 103.340417
          }
        ],
        "looping": false,
        "autoplay": true,
        "reverbConfig": {
          "mix": 0.3,
          "damp": 0.5,
          "width": 0.8,
          "enabled": false,
          "roomSize": 0.5,
          "predelayMs": 20
        },
        "showWaveform": true,
        "blinkieColors": {
          "text": "#ccc0e0",
          "buttons": "#a84888",
          "innerBox": "#6a4898",
          "outerBox": "#1a1530",
          "playerBox": "#483570"
        },
        "phoneHomeLayout": {
          "col": 0,
          "row": 0,
          "page": 1,
          "width": 4,
          "height": 1
        },
        "phoneHomeWidgetMode": true,
        "blinkieBoxBackgrounds": {
          "cardBgUrl": "/card-backgrounds/green-orbits.gif"
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a4",
      "is_visible": false
    },
    {
      "card_type": "link",
      "title": "SHOWS",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "appIconUrl": "/icons/mac/font-suitcase.png",
        "verticalAlign": "middle",
        "phoneHomeLayout": {
          "col": 2,
          "row": 0,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a5",
      "is_visible": true
    },
    {
      "card_type": "music",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "title": "Take Da Charge",
        "embedUrl": "https://open.spotify.com/track/2XOKoaCWziW0W14DPeY7XS?si=b551f5abeb964d19",
        "platform": "spotify",
        "appIconUrl": "/icons/8bit/8bit46.png",
        "embeddable": true,
        "thumbnailUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02393fb413d09de1443185da1e",
        "embedIframeUrl": "https://open.spotify.com/embed/track/2XOKoaCWziW0W14DPeY7XS?si=b551f5abeb964d19&theme=0",
        "phoneHomeLayout": {
          "col": 0,
          "row": 3,
          "page": 0,
          "width": 4,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a6",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "calcMessage": "idiot",
        "macWindowStyle": "calculator",
        "scatterLayouts": {
          "mac-os": {
            "x": 40,
            "y": 30.000000000000007,
            "width": 60,
            "height": 40,
            "zIndex": 5
          },
          "word-art": {
            "x": 40,
            "y": 30.000000000000007,
            "width": 60,
            "height": 40,
            "zIndex": 5
          },
          "macintosh": {
            "x": 40,
            "y": 30.000000000000007,
            "width": 60,
            "height": 40,
            "zIndex": 5
          },
          "instagram-reels": {
            "x": 40,
            "y": 30.000000000000007,
            "width": 60,
            "height": 40,
            "zIndex": 5
          },
          "system-settings": {
            "x": 40,
            "y": 30.000000000000007,
            "width": 60,
            "height": 40,
            "zIndex": 5
          }
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a7",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "macWindowStyle": "map",
        "scatterLayouts": {
          "mac-os": {
            "x": 0,
            "y": 60,
            "width": 60,
            "height": 40,
            "zIndex": 6
          },
          "word-art": {
            "x": 0,
            "y": 60,
            "width": 60,
            "height": 40,
            "zIndex": 6
          },
          "macintosh": {
            "x": 0,
            "y": 60,
            "width": 60,
            "height": 40,
            "zIndex": 6
          },
          "instagram-reels": {
            "x": 0,
            "y": 60,
            "width": 60,
            "height": 40,
            "zIndex": 6
          },
          "system-settings": {
            "x": 0,
            "y": 60,
            "width": 60,
            "height": 40,
            "zIndex": 6
          }
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a8",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "macMode": "video",
        "macVideoUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-videos/01ec9b3e-c7fc-4722-87fd-3c388421b680/1a4185d0-4427-44fd-88ae-d0832e9860f3.mp4",
        "macTextAlign": "center",
        "macTextColor": "#ffffff",
        "macWindowStyle": "small-window",
        "macCheckerColor": "#8f5685",
        "macWindowBgColor": "#6895a1",
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a9",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": "BAkANI",
      "description": null,
      "url": null,
      "content": {
        "macMode": "link",
        "macTextAlign": "center",
        "macTextColor": "#000",
        "macWindowStyle": "small-window",
        "macCheckerColor": "#8f5685",
        "macWindowBgColor": "#6895a1",
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "aA",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "macLinks": [
          {
            "url": "",
            "title": "LISTEN"
          },
          {
            "url": "",
            "title": "WATCH"
          },
          {
            "url": "",
            "title": "MORE"
          },
          {
            "url": "",
            "title": "SHOWS"
          }
        ],
        "notepadStyle": "buttons",
        "macWindowStyle": "notepad",
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "aB",
      "is_visible": false
    }
  ],
  "theme": {
    "themeId": "chaotic-zine",
    "paletteId": "classic-zine",
    "colors": {
      "link": "#050505",
      "text": "#050505",
      "accent": "#ff3b3b",
      "border": "#050505",
      "cardBg": "#050505",
      "background": "#f4f4f0"
    },
    "fonts": {
      "body": "var(--font-special-elite)",
      "heading": "var(--font-permanent-marker)",
      "bodySize": 1,
      "headingSize": 1.4,
      "headingWeight": "normal"
    },
    "style": {
      "borderRadius": 0,
      "blurIntensity": 0,
      "shadowEnabled": false
    },
    "background": {
      "type": "image",
      "value": ""
    },
    "cardTypeFontSizes": {
      "hero": 0.6,
      "square": 1.4,
      "horizontal": 0.9,
      "link": 1,
      "mini": 1,
      "text": 1.3,
      "gallery": 1,
      "video": 1.8
    },
    "centerCards": false,
    "vcrCenterContent": true,
    "receiptPrice": "A GAJILLON ",
    "receiptStickers": [
      {
        "x": 4.765215498697749,
        "y": 1.4389843466185646,
        "id": "price-tag-2-1770970704453",
        "src": "/images/stickers/price-tag-2.jpeg",
        "scale": 1.0261351575739197,
        "rotation": 13.740950510664732,
        "behindText": false
      }
    ],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": true,
    "ipodStickers": [
      {
        "x": 48.73754500089153,
        "y": 91.25863511095115,
        "id": "price-tag-1-1770680564846",
        "src": "/images/stickers/price-tag-1.jpeg",
        "scale": 0.9,
        "rotation": 3,
        "behindText": true
      }
    ],
    "ipodTexture": "/images/ipod-texture-rusty.jpeg",
    "ipodFont": "system",
    "macPattern": "",
    "macPatternColor": "#a37710",
    "wordArtTitleStyle": "style-four",
    "lanyardActiveView": 0,
    "classifiedStampText": "fuck you",
    "classifiedDeptText": "idiot",
    "classifiedCenterText": "idiot brain",
    "classifiedMessageText": "shut up",
    "phoneHomeDock": [],
    "phoneHomeShowDock": true,
    "phoneHomeVariant": "8-bit",
    "zineBadgeText": "",
    "zineTitleSize": 0.9,
    "zineShowDoodles": false,
    "scatterMode": false,
    "visitorDrag": false
  },
  "profile": {
    "profileLayout": "classic",
    "showAvatar": true,
    "showTitle": true,
    "titleSize": "large",
    "showSocialIcons": true,
    "showLogo": false,
    "headerTextColor": "oklch(0 0 0)",
    "socialIconColor": "oklch(0 0 0)"
  },
  "mediaAssets": [],
  "id": "chaotic-zine-o-g",
  "name": "O.G",
  "description": "CLEAN TEMPLATE",
  "thumbnailPath": "/templates/chaotic-zine-o-g/thumbnail.jpg"
} as const satisfies TemplateDefinition
