// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const chaoticZineSimpleNew: TemplateDefinition = {
  "themeId": "chaotic-zine",
  "cards": [
    {
      "card_type": "hero",
      "title": "LISTEN",
      "description": null,
      "url": null,
      "content": {
        "iconName": "Music",
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/my-computer.png",
        "showButton": false,
        "wordArtStyle": "style-four",
        "transparentBackground": false
      },
      "size": "small",
      "position": "center",
      "sortKey": "a0",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": "VIDEOS",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "textAlign": "center",
        "appIconUrl": "/icons/8bit/folder.png",
        "showButton": false,
        "wordArtStyle": "style-seven",
        "transparentBackground": false
      },
      "size": "small",
      "position": "center",
      "sortKey": "a1",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "TOUR DATES",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "appIconUrl": "/icons/8bit/sound.png",
        "wordArtStyle": "style-twentyone",
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a2",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "MERCH",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "appIconUrl": "/icons/8bit/calculator.png",
        "wordArtStyle": "style-fourteen",
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a3",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "YOUTUBE",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "appIconUrl": "/icons/8bit/internet-explorer.png",
        "wordArtStyle": "style-three",
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a4",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "INSTAGRAM",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "appIconUrl": "/icons/8bit/my-documents.png",
        "wordArtStyle": "style-seventeen",
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a5",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "WEBISTE",
      "description": null,
      "url": null,
      "content": {
        "iconName": "MapPin",
        "appIconUrl": "/icons/8bit/notepad.png",
        "wordArtStyle": "style-one",
        "phoneHomeLayout": {
          "col": 2,
          "row": 1,
          "page": 0,
          "width": 1,
          "height": 1
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "center",
      "sortKey": "a6",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "macLinks": [
          {
            "url": "https://open.spotify.com/album/",
            "title": "LISTEN"
          },
          {
            "url": "https://bandsintown.com/",
            "title": "VIDEOS"
          },
          {
            "url": "https://bandsintown.com/",
            "title": "TOUR DATES"
          },
          {
            "url": "https://bandsintown.com/",
            "title": "MERCH"
          }
        ],
        "notepadStyle": "buttons",
        "macWindowStyle": "notepad"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a9",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": "LINK OR VIDEO",
      "description": null,
      "url": null,
      "content": {
        "macMode": "link",
        "macTextAlign": "left",
        "macTextColor": "#000000",
        "macWindowStyle": "small-window",
        "macCheckerColor": "#cfffcc",
        "macWindowBgColor": "#afb3ee"
      },
      "size": "big",
      "position": "left",
      "sortKey": "aA",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": "LINK OR VIDEO",
      "description": null,
      "url": null,
      "content": {
        "macMode": "link",
        "macTextAlign": "left",
        "macTextColor": "#000",
        "macWindowStyle": "small-window",
        "macCheckerColor": "#cfffcc",
        "macWindowBgColor": "#afb3ee"
      },
      "size": "big",
      "position": "left",
      "sortKey": "aB",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "calcMessage": "custom message ",
        "macWindowStyle": "calculator"
      },
      "size": "big",
      "position": "left",
      "sortKey": "aC",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "macWindowStyle": "map"
      },
      "size": "big",
      "position": "left",
      "sortKey": "aE",
      "is_visible": false
    },
    {
      "card_type": "hero",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "albumArtUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/9b437c15-d956-4b88-9b2e-3c1681fec566/85a9c56a-9544-41db-b943-26d16c0610cb.jpg",
        "showCountdown": true,
        "macWindowStyle": "presave",
        "presaveBgColor": "#F2FFA4",
        "preSaveButtonText": "Pre-save",
        "afterCountdownText": "OUT NOW",
        "albumArtStoragePath": "9b437c15-d956-4b88-9b2e-3c1681fec566/85a9c56a-9544-41db-b943-26d16c0610cb.jpg",
        "afterCountdownAction": "custom"
      },
      "size": "big",
      "position": "left",
      "sortKey": "aH",
      "is_visible": false
    }
  ],
  "theme": {
    "themeId": "chaotic-zine",
    "paletteId": "classic-zine",
    "colors": {
      "background": "#f4f4f0",
      "cardBg": "#050505",
      "text": "#050505",
      "accent": "#ff3b3b",
      "border": "#050505",
      "link": "#050505"
    },
    "fonts": {
      "heading": "var(--font-permanent-marker)",
      "body": "var(--font-special-elite)",
      "headingSize": 1.4,
      "bodySize": 1,
      "headingWeight": "normal"
    },
    "style": {
      "borderRadius": 0,
      "shadowEnabled": false,
      "blurIntensity": 0
    },
    "background": {
      "type": "solid",
      "value": "#f4f4f0"
    },
    "cardTypeFontSizes": {
      "hero": 0.8,
      "square": 1,
      "horizontal": 1,
      "link": 1.2,
      "mini": 1,
      "text": 1,
      "gallery": 1,
      "video": 1
    },
    "centerCards": false,
    "vcrCenterContent": false,
    "receiptPrice": "PRICELESS",
    "receiptStickers": [],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": false,
    "ipodStickers": [],
    "ipodTexture": "/images/ipod-texture-scratched.jpeg",
    "ipodFont": "system",
    "macPattern": "/images/mac-patterns/pattern-1.png",
    "macPatternColor": "#7e350d",
    "wordArtTitleStyle": "style-three",
    "phoneHomeDock": [],
    "phoneHomeShowDock": true,
    "phoneHomeVariant": "default",
    "zineBadgeText": "NEW!",
    "zineTitleSize": 0.6,
    "zineShowDoodles": false,
    "artifactMarqueeText": "LINKS_DATABASE /// ACCESS_GRANTED >>> CONNECT_NOW /// NET_RUNNER",
    "artifactHeaderTopLeft": "USER.ID_99",
    "artifactHeaderTopCenter": "[ONLINE]",
    "artifactHeaderTopRight": "",
    "artifactHeaderBottomLeft": "DIGITAL // PHY",
    "artifactHeaderBottomCenter": "///",
    "artifactHeaderBottomRight": "SYS_ADMIN",
    "artifactShowHeaderMeta": true,
    "artifactHeroOverlay": true,
    "artifactHeroMediaType": "image",
    "artifactHeroImageUrl": "",
    "artifactHeroVideoUrl": "",
    "artifactHeroPositionX": 50,
    "artifactHeroPositionY": 50,
    "scatterMode": false,
    "visitorDrag": false
  },
  "profile": {
    "displayName": "YOUR NAME",
    "bio": "BIO",
    "avatarUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/profile-images/36eb6d57-7a64-458a-aafa-16e076ead485/avatar-92d08289-49e4-4b18-a0a5-c29feb16f844.jpg",
    "avatarFeather": 0,
    "showAvatar": true,
    "showTitle": true,
    "titleSize": "small",
    "showSocialIcons": true,
    "showLogo": false,
    "logoUrl": null,
    "logoScale": 100,
    "profileLayout": "classic",
    "headerTextColor": "#ffffff",
    "socialIconColor": "#ffffff",
    "socialIcons": [
      {
        "id": "86ec3c07-a25a-4aaf-b063-98ae75cf1fa8",
        "url": "",
        "sortKey": "a1",
        "platform": "instagram"
      },
      {
        "id": "144c3a93-9040-471f-86d9-cacda54921ff",
        "url": "",
        "sortKey": "a2",
        "platform": "spotify"
      },
      {
        "id": "8d4ad2df-d302-4e46-a9f6-a4f19633c261",
        "url": "",
        "sortKey": "a3",
        "platform": "tiktok"
      }
    ]
  },
  "mediaAssets": [],
  "id": "chaotic-zine-simple-new",
  "name": "SIMPLE (NEW)",
  "description": "SIMPLE (NEW) template",
  "thumbnailPath": "/templates/chaotic-zine-simple-new/thumbnail.jpg"
} as const satisfies TemplateDefinition
