// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const systemSettingsHawaii: TemplateDefinition = {
  "themeId": "system-settings",
  "cards": [
    {
      "card_type": "link",
      "title": "INSTAGRAM",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "showButton": true,
        "buttonStyle": "outline",
        "verticalAlign": "middle",
        "transparentBackground": true
      },
      "size": "big",
      "position": "left",
      "sortKey": "Zx",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "WEBSITE",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "verticalAlign": "top",
        "transparentBackground": true
      },
      "size": "big",
      "position": "left",
      "sortKey": "ZxG",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "YOUTUBE",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "verticalAlign": "center",
        "transparentBackground": true
      },
      "size": "big",
      "position": "left",
      "sortKey": "ZxI",
      "is_visible": true
    },
    {
      "card_type": "audio",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "tracks": [
          {
            "id": "ce94b743-3569-4a2a-8716-49a0308b9e02",
            "title": "Plantasia",
            "artist": "",
            "audioUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-audio/e85b97cb-b3b7-47a2-b54c-2d59f1cb58e0/ce94b743-3569-4a2a-8716-49a0308b9e02.mp3",
            "duration": 201.178333
          }
        ],
        "looping": false,
        "autoplay": false,
        "reverbConfig": {
          "mix": 0.3,
          "damp": 0.5,
          "width": 0.8,
          "enabled": true,
          "roomSize": 0.5,
          "predelayMs": 20
        },
        "showWaveform": true,
        "blinkieColors": {
          "text": "#000000",
          "buttons": "#F9F0E9",
          "innerBox": "#EDE4DA",
          "outerBox": "#F9F0E9",
          "playerBox": "#F9F0E9"
        },
        "scatterLayouts": {
          "instagram-reels": {
            "x": 0,
            "y": 80.32,
            "width": 100,
            "height": 10,
            "zIndex": 2
          }
        },
        "blinkieBoxBackgrounds": {
          "cardBgUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/e85b97cb-b3b7-47a2-b54c-2d59f1cb58e0/33ca4e30-ba5b-4182-be9e-f96c7772ff76.jpg",
          "cardOuterDim": 2,
          "cardBgStoragePath": "e85b97cb-b3b7-47a2-b54c-2d59f1cb58e0/33ca4e30-ba5b-4182-be9e-f96c7772ff76.jpg"
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "ZxK",
      "is_visible": true
    },
    {
      "card_type": "square",
      "title": "NEW SONG ",
      "description": null,
      "url": null,
      "content": {
        "imageUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/502b8c8f-f30a-4fec-b80a-578f9c1c136d/76daeba0-3585-42a7-9329-ecedee93f89b.jpg",
        "textAlign": "center",
        "verticalAlign": "bottom",
        "scatterLayouts": {
          "instagram-reels": {
            "x": 0,
            "y": 224.83074626865672,
            "width": 47.67,
            "height": 10,
            "zIndex": 16
          }
        },
        "transparentBackground": true
      },
      "size": "small",
      "position": "right",
      "sortKey": "ZxS",
      "is_visible": true
    },
    {
      "card_type": "square",
      "title": "ALBUM OUT",
      "description": "out now ",
      "url": null,
      "content": {
        "imageUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/3ffddf52-ac4b-4bf5-ac8b-2b17e86299b3/ba1d30f2-2bd0-4777-ba95-13f64e58a616.png",
        "textAlign": "center",
        "verticalAlign": "bottom",
        "scatterLayouts": {
          "instagram-reels": {
            "x": 52.32985074626866,
            "y": 244.53223880597014,
            "width": 47.67,
            "height": 10,
            "zIndex": 15
          }
        },
        "transparentBackground": true
      },
      "size": "small",
      "position": "left",
      "sortKey": "ZxSV",
      "is_visible": true
    },
    {
      "card_type": "music",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "autoplay": false,
        "embedUrl": "https://open.spotify.com/embed/track/7twektvD4cCkF5LeXq9yqU?utm_source=generator",
        "noBorder": false,
        "platform": "spotify",
        "embeddable": true,
        "embedHeight": 152,
        "embedIframeUrl": "https://open.spotify.com/embed/track/7twektvD4cCkF5LeXq9yqU?utm_source=generator",
        "phoneHomeWidgetSize": "wide",
        "transparentBackground": true
      },
      "size": "big",
      "position": "left",
      "sortKey": "ZxT",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "TIKTOK",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "embedHeight": null,
        "verticalAlign": "center",
        "embedIframeUrl": null,
        "transparentBackground": true
      },
      "size": "big",
      "position": "left",
      "sortKey": "Zxk",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "EP LAUNCH",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "verticalAlign": "center",
        "transparentBackground": true
      },
      "size": "big",
      "position": "left",
      "sortKey": "Zy",
      "is_visible": true
    },
    {
      "card_type": "social-icons",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "scatterLayouts": {
          "instagram-reels": {
            "x": 37.34311914738806,
            "y": 171.46242761881996,
            "width": 97.45299839142088,
            "height": 10,
            "zIndex": 22
          }
        },
        "transparentBackground": true
      },
      "size": "big",
      "position": "left",
      "sortKey": "a8",
      "is_visible": true
    }
  ],
  "theme": {
    "themeId": "system-settings",
    "paletteId": null,
    "colors": {
      "link": "oklch(0.35 0.12 250)",
      "text": "#fafaeb",
      "accent": "oklch(1 0 0)",
      "border": "oklch(0.20 0 0)",
      "cardBg": "oklch(0.95 0.02 70)",
      "background": "oklch(0.89 0.04 10)"
    },
    "fonts": {
      "body": "var(--font-dm-sans)",
      "heading": "var(--font-chiq)",
      "bodySize": 0.875,
      "headingSize": 1.125,
      "headingWeight": "normal"
    },
    "style": {
      "borderRadius": 6,
      "blurIntensity": 0,
      "shadowEnabled": false
    },
    "background": {
      "type": "image",
      "value": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/36eb6d57-7a64-458a-aafa-16e076ead485/backgrounds/1772085265965.jpg",
      "dimOverlay": true,
      "glitchType": "crt",
      "dimIntensity": 45,
      "glitchEffect": false,
      "noiseOverlay": true,
      "glitchFullPage": false,
      "noiseIntensity": 14,
      "glitchCrtPreset": "computer-monitor",
      "glitchIntensity": 45,
      "glitchSyncError": 55,
      "glitchPixelShape": "cross",
      "glitchCrtCurvature": 2,
      "glitchCrtScanlines": 20,
      "glitchDigitalNoise": 0,
      "glitchCrtAberration": 75,
      "glitchSignalDropout": 5,
      "glitchCrtPhosphorGlow": 0,
      "glitchLineDisplacement": 0,
      "glitchCrtScanlineThickness": 15
    },
    "cardTypeFontSizes": {
      "hero": 0.9,
      "square": 1.3,
      "horizontal": 1,
      "link": 1.1,
      "mini": 1,
      "text": 1,
      "gallery": 1,
      "video": 1
    },
    "centerCards": true,
    "vcrCenterContent": false,
    "receiptPrice": "PRICELESS",
    "receiptStickers": [],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": false,
    "ipodStickers": [],
    "ipodTexture": "/images/metal-texture.jpeg",
    "ipodFont": "system",
    "macPattern": "",
    "macPatternColor": "#c0c0c0",
    "wordArtTitleStyle": "style-eleven",
    "phoneHomeDock": [],
    "phoneHomeShowDock": true,
    "phoneHomeDockTranslucent": true,
    "phoneHomeVariant": "default",
    "zineBadgeText": "NEW!",
    "zineTitleSize": 1,
    "zineShowDoodles": true,
    "artifactMarqueeText": "LINKS_DATABASE /// ACCESS_GRANTED >>> CONNECT_NOW /// NET_RUNNER",
    "artifactHeaderTopLeft": "USER.ID_99",
    "artifactHeaderTopCenter": "[ONLINE]",
    "artifactHeaderTopRight": "",
    "artifactHeaderBottomLeft": "DIGITAL // PHY",
    "artifactHeaderBottomCenter": "///",
    "artifactHeaderBottomRight": "SYS_ADMIN",
    "artifactShowHeaderMeta": true,
    "artifactHeroOverlay": true,
    "artifactHeroMediaType": "image",
    "artifactHeroImageUrl": "",
    "artifactHeroVideoUrl": "",
    "artifactHeroPositionX": 50,
    "artifactHeroPositionY": 50,
    "scatterMode": false,
    "visitorDrag": false
  },
  "profile": {
    "displayName": "Kook Joey",
    "bio": "MUSIC MAKER",
    "avatarUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/profile-images/36eb6d57-7a64-458a-aafa-16e076ead485/avatar-4e470079-e33d-4948-9e23-f1496512482e.jpg",
    "avatarFeather": 10,
    "avatarSize": 148,
    "showAvatar": true,
    "showTitle": true,
    "titleSize": "large",
    "showSocialIcons": true,
    "showLogo": false,
    "logoUrl": null,
    "logoScale": 100,
    "profileLayout": "classic",
    "headerTextColor": "#fafaeb",
    "socialIconColor": "#fafaeb",
    "socialIcons": [
      {
        "id": "06515d9e-6d56-4456-a44f-7db202074a37",
        "url": "",
        "sortKey": "a0",
        "platform": "instagram"
      },
      {
        "id": "b6575a11-c121-4474-a21c-b0cd366d4387",
        "url": "",
        "sortKey": "a1",
        "platform": "youtube"
      },
      {
        "id": "a609ffe5-a979-456a-8bd7-0c6a6c14f1c5",
        "url": "",
        "sortKey": "a2",
        "platform": "spotify"
      }
    ]
  },
  "mediaAssets": [],
  "id": "system-settings-hawaii",
  "name": "HAWAII",
  "description": "HAWAII template",
  "thumbnailPath": "/templates/system-settings-hawaii/thumbnail.jpg"
} as const satisfies TemplateDefinition
