// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const systemSettingsMakeItRed: TemplateDefinition = {
  "themeId": "system-settings",
  "cards": [
    {
      "card_type": "social-icons",
      "title": null,
      "description": null,
      "url": null,
      "content": {},
      "size": "big",
      "position": "left",
      "sortKey": "a0",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "LINK",
      "description": null,
      "url": "https://open.spotify.com/album/",
      "content": {
        "iconName": "Music"
      },
      "size": "big",
      "position": "center",
      "sortKey": "a1",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "LINK",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin"
      },
      "size": "big",
      "position": "center",
      "sortKey": "a1V",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "LINK",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin"
      },
      "size": "big",
      "position": "center",
      "sortKey": "a2",
      "is_visible": true
    },
    {
      "card_type": "audio",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "tracks": [],
        "looping": false,
        "reverbConfig": {
          "mix": 0.3,
          "damp": 0.5,
          "width": 0.8,
          "enabled": false,
          "roomSize": 0.5,
          "predelayMs": 20
        },
        "showWaveform": true
      },
      "size": "big",
      "position": "left",
      "sortKey": "a2V",
      "is_visible": true
    },
    {
      "card_type": "square",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "verticalAlign": "bottom"
      },
      "size": "small",
      "position": "left",
      "sortKey": "a3",
      "is_visible": true
    },
    {
      "card_type": "square",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "verticalAlign": "bottom"
      },
      "size": "small",
      "position": "left",
      "sortKey": "a4",
      "is_visible": true
    },
    {
      "card_type": "release",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "showCountdown": true,
        "preSaveButtonText": "Pre-save",
        "afterCountdownText": "OUT NOW",
        "afterCountdownAction": "custom"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a5",
      "is_visible": true
    }
  ],
  "theme": {
    "themeId": "system-settings",
    "paletteId": "red-label",
    "colors": {
      "background": "#ffffff",
      "cardBg": "#ac0000",
      "text": "#ffffff",
      "accent": "#a70000",
      "border": "#ffffff",
      "link": "#a70000",
      "titleBarLine": "#ffffff"
    },
    "fonts": {
      "heading": "var(--font-ishmeria)",
      "body": "var(--font-dm-sans)",
      "headingSize": 1,
      "bodySize": 1,
      "headingWeight": "normal"
    },
    "style": {
      "borderRadius": 6,
      "shadowEnabled": false,
      "blurIntensity": 0
    },
    "background": {
      "type": "solid",
      "value": "#ffffff"
    },
    "cardTypeFontSizes": {
      "hero": 1,
      "square": 1,
      "horizontal": 1,
      "link": 1,
      "mini": 1,
      "text": 1,
      "gallery": 1,
      "video": 1
    },
    "centerCards": true,
    "vcrCenterContent": false,
    "receiptPrice": "PRICELESS",
    "receiptStickers": [],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": false,
    "ipodStickers": [],
    "ipodTexture": "/images/metal-texture.jpeg",
    "ipodFont": "system",
    "macPattern": "",
    "macPatternColor": "#c0c0c0",
    "wordArtTitleStyle": "style-eleven",
    "phoneHomeDock": [],
    "phoneHomeShowDock": true,
    "phoneHomeVariant": "default",
    "zineBadgeText": "NEW!",
    "zineTitleSize": 1,
    "zineShowDoodles": true,
    "artifactMarqueeText": "LINKS_DATABASE /// ACCESS_GRANTED >>> CONNECT_NOW /// NET_RUNNER",
    "artifactHeaderTopLeft": "USER.ID_99",
    "artifactHeaderTopCenter": "[ONLINE]",
    "artifactHeaderTopRight": "",
    "artifactHeaderBottomLeft": "DIGITAL // PHY",
    "artifactHeaderBottomCenter": "///",
    "artifactHeaderBottomRight": "SYS_ADMIN",
    "artifactShowHeaderMeta": true,
    "artifactHeroOverlay": true,
    "artifactHeroMediaType": "image",
    "artifactHeroImageUrl": "",
    "artifactHeroVideoUrl": "",
    "artifactHeroPositionX": 50,
    "artifactHeroPositionY": 50,
    "scatterMode": false,
    "visitorDrag": false
  },
  "profile": {
    "displayName": "YOUR NAME",
    "bio": null,
    "avatarUrl": null,
    "avatarFeather": 0,
    "showAvatar": true,
    "showTitle": true,
    "titleSize": "small",
    "showSocialIcons": true,
    "showLogo": false,
    "logoUrl": null,
    "logoScale": 100,
    "profileLayout": "classic",
    "headerTextColor": "#be1818",
    "socialIconColor": "#b70000",
    "socialIcons": [
      {
        "id": "d720a696-fcb5-4ec2-aa37-a5ca2e749027",
        "url": "",
        "sortKey": "a0",
        "platform": "twitter"
      },
      {
        "id": "86ec3c07-a25a-4aaf-b063-98ae75cf1fa8",
        "url": "",
        "sortKey": "a1",
        "platform": "instagram"
      },
      {
        "id": "144c3a93-9040-471f-86d9-cacda54921ff",
        "url": "",
        "sortKey": "a2",
        "platform": "spotify"
      },
      {
        "id": "8d4ad2df-d302-4e46-a9f6-a4f19633c261",
        "url": "",
        "sortKey": "a3",
        "platform": "tiktok"
      }
    ]
  },
  "mediaAssets": [],
  "id": "system-settings-make-it-red",
  "name": "MAKE IT RED",
  "description": "MAKE IT RED template",
  "thumbnailPath": "/templates/system-settings-make-it-red/thumbnail.jpg"
} as const satisfies TemplateDefinition
