// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const systemSettingsQuiteBeskoke: TemplateDefinition = {
  "themeId": "system-settings",
  "cards": [
    {
      "card_type": "social-icons",
      "title": null,
      "description": null,
      "url": null,
      "content": {},
      "size": "big",
      "position": "left",
      "sortKey": "a0",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "LINK",
      "description": null,
      "url": "https://open.spotify.com/album/",
      "content": {
        "iconName": "Music",
        "transparentBackground": true
      },
      "size": "big",
      "position": "center",
      "sortKey": "a1",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "LINK",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "transparentBackground": true
      },
      "size": "big",
      "position": "center",
      "sortKey": "a2",
      "is_visible": true
    },
    {
      "card_type": "square",
      "title": "LINK",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "transparentBackground": true
      },
      "size": "small",
      "position": "center",
      "sortKey": "a3",
      "is_visible": true
    },
    {
      "card_type": "square",
      "title": "LINK",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "transparentBackground": true
      },
      "size": "small",
      "position": "center",
      "sortKey": "a4",
      "is_visible": true
    },
    {
      "card_type": "audio",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "tracks": [],
        "looping": false,
        "reverbConfig": {
          "mix": 0.3,
          "damp": 0.5,
          "width": 0.8,
          "enabled": false,
          "roomSize": 0.5,
          "predelayMs": 20
        },
        "showWaveform": true,
        "blinkieColors": {
          "text": "#e8dcc8",
          "buttons": "#d85828",
          "innerBox": "#c89848",
          "outerBox": "#352518",
          "playerBox": "#987040"
        },
        "blinkieBoxBackgrounds": {
          "cardBgUrl": "/card-backgrounds/cd-holographic.gif"
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a5",
      "is_visible": true
    },
    {
      "card_type": "text",
      "title": "LINK",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "transparentBackground": true
      },
      "size": "small",
      "position": "center",
      "sortKey": "a6",
      "is_visible": true
    },
    {
      "card_type": "text",
      "title": "LINK",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "transparentBackground": true
      },
      "size": "small",
      "position": "center",
      "sortKey": "a7",
      "is_visible": true
    }
  ],
  "theme": {
    "themeId": "system-settings",
    "paletteId": "poolsuite-pink",
    "colors": {
      "background": "oklch(0.89 0.04 10)",
      "cardBg": "oklch(0.95 0.02 70)",
      "text": "oklch(0 0 0)",
      "accent": "oklch(1 0 0)",
      "border": "oklch(0.20 0 0)",
      "link": "oklch(0.35 0.12 250)"
    },
    "fonts": {
      "heading": "var(--font-ishmeria)",
      "body": "var(--font-dm-sans)",
      "headingSize": 1,
      "bodySize": 1,
      "headingWeight": "normal"
    },
    "style": {
      "borderRadius": 6,
      "shadowEnabled": false,
      "blurIntensity": 0
    },
    "background": {
      "type": "solid",
      "value": "oklch(0.89 0.04 10)"
    },
    "cardTypeFontSizes": {
      "hero": 1,
      "square": 1,
      "horizontal": 1,
      "link": 1,
      "mini": 1,
      "text": 1.3,
      "gallery": 1,
      "video": 1
    },
    "centerCards": true,
    "vcrCenterContent": false,
    "receiptPrice": "PRICELESS",
    "receiptStickers": [],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": false,
    "ipodStickers": [],
    "ipodTexture": "/images/metal-texture.jpeg",
    "ipodFont": "system",
    "macPattern": "",
    "macPatternColor": "#c0c0c0",
    "wordArtTitleStyle": "style-eleven",
    "phoneHomeDock": [],
    "phoneHomeShowDock": true,
    "phoneHomeDockTranslucent": true,
    "phoneHomeVariant": "default",
    "zineBadgeText": "NEW!",
    "zineTitleSize": 1,
    "zineShowDoodles": true,
    "artifactMarqueeText": "LINKS_DATABASE /// ACCESS_GRANTED >>> CONNECT_NOW /// NET_RUNNER",
    "artifactHeaderTopLeft": "USER.ID_99",
    "artifactHeaderTopCenter": "[ONLINE]",
    "artifactHeaderTopRight": "",
    "artifactHeaderBottomLeft": "DIGITAL // PHY",
    "artifactHeaderBottomCenter": "///",
    "artifactHeaderBottomRight": "SYS_ADMIN",
    "artifactShowHeaderMeta": true,
    "artifactHeroOverlay": true,
    "artifactHeroMediaType": "image",
    "artifactHeroImageUrl": "",
    "artifactHeroVideoUrl": "",
    "artifactHeroPositionX": 50,
    "artifactHeroPositionY": 50,
    "scatterMode": false,
    "visitorDrag": false
  },
  "profile": {
    "displayName": "YOUR NAME",
    "bio": null,
    "avatarUrl": null,
    "avatarFeather": 0,
    "showAvatar": true,
    "showTitle": true,
    "titleSize": "small",
    "showSocialIcons": true,
    "showLogo": false,
    "logoUrl": null,
    "logoScale": 100,
    "profileLayout": "classic",
    "headerTextColor": "oklch(0 0 0)",
    "socialIconColor": "oklch(0 0 0)",
    "socialIcons": [
      {
        "id": "1757f885-bebc-4bd3-9962-177d8aa6c3ba",
        "url": "",
        "sortKey": "a0",
        "platform": "instagram"
      },
      {
        "id": "7b5b63b1-4169-4075-b2b3-cdbc0472802a",
        "url": "",
        "sortKey": "a1",
        "platform": "bandcamp"
      },
      {
        "id": "5c8e9f53-b73b-404e-98dc-49ca133d6d2b",
        "url": "",
        "sortKey": "a2",
        "platform": "spotify"
      },
      {
        "id": "83fc5d2f-2d05-4e01-8106-d255fa70c886",
        "url": "",
        "sortKey": "a3",
        "platform": "applemusic"
      }
    ]
  },
  "mediaAssets": [],
  "id": "system-settings-quite-beskoke",
  "name": "QUITE BESPOKE",
  "description": "QUITE BESKOKE template",
  "thumbnailPath": "/templates/system-settings-quite-beskoke/thumbnail.jpg"
} as const satisfies TemplateDefinition
