// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const systemSettingsSpreadThemOut: TemplateDefinition = {
  "themeId": "system-settings",
  "cards": [
    {
      "card_type": "social-icons",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "scatterLayouts": {
          "system-settings": {
            "x": 31.04127798507463,
            "y": 217.91744402985077,
            "width": 100,
            "height": 10,
            "zIndex": 40
          }
        }
      },
      "size": "big",
      "position": "left",
      "sortKey": "a0",
      "is_visible": true
    },
    {
      "card_type": "text",
      "title": "LINK",
      "description": null,
      "url": "https://open.spotify.com/album/",
      "content": {
        "iconName": "Music",
        "scatterLayouts": {
          "system-settings": {
            "x": 31.525074626865667,
            "y": 23.421731343283582,
            "width": 192.26424798242704,
            "height": 10,
            "zIndex": 77
          }
        },
        "transparentBackground": true
      },
      "size": "big",
      "position": "center",
      "sortKey": "a1",
      "is_visible": true
    },
    {
      "card_type": "text",
      "title": "LINK",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "scatterLayouts": {
          "system-settings": {
            "x": 34.02985074626866,
            "y": 6.865671641791045,
            "width": 100,
            "height": 10,
            "zIndex": 73
          }
        },
        "transparentBackground": true
      },
      "size": "big",
      "position": "center",
      "sortKey": "a2",
      "is_visible": true
    },
    {
      "card_type": "text",
      "title": "LINK",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "scatterLayouts": {
          "system-settings": {
            "x": 46.049552238805965,
            "y": 56.058208955223876,
            "width": 162.385112532883,
            "height": 10,
            "zIndex": 69
          }
        },
        "transparentBackground": true
      },
      "size": "small",
      "position": "center",
      "sortKey": "a3",
      "is_visible": true
    },
    {
      "card_type": "text",
      "title": "LINK",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "scatterLayouts": {
          "system-settings": {
            "x": 71.34328358208955,
            "y": 31.412835820895523,
            "width": 100,
            "height": 10,
            "zIndex": 71
          }
        },
        "transparentBackground": true
      },
      "size": "small",
      "position": "center",
      "sortKey": "a3V",
      "is_visible": true
    },
    {
      "card_type": "text",
      "title": "LINK",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "scatterLayouts": {
          "system-settings": {
            "x": 68.65671641791045,
            "y": 48.72626865671642,
            "width": 100,
            "height": 10,
            "zIndex": 65
          }
        },
        "transparentBackground": true
      },
      "size": "small",
      "position": "center",
      "sortKey": "a3l",
      "is_visible": true
    },
    {
      "card_type": "text",
      "title": "LINK",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "scatterLayouts": {
          "system-settings": {
            "x": 13.432835820895523,
            "y": 22.580298507462686,
            "width": 100,
            "height": 10,
            "zIndex": 74
          }
        },
        "transparentBackground": true
      },
      "size": "small",
      "position": "center",
      "sortKey": "a4",
      "is_visible": true
    },
    {
      "card_type": "audio",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "tracks": [],
        "looping": false,
        "reverbConfig": {
          "mix": 0.3,
          "damp": 0.5,
          "width": 0.8,
          "enabled": false,
          "roomSize": 0.5,
          "predelayMs": 20
        },
        "showWaveform": true,
        "blinkieColors": {
          "text": "#e8dcc8",
          "buttons": "#d85828",
          "innerBox": "#c89848",
          "outerBox": "#352518",
          "playerBox": "#987040"
        },
        "scatterLayouts": {
          "system-settings": {
            "x": 0,
            "y": 81.35503731343285,
            "width": 100,
            "height": 10,
            "zIndex": 43
          }
        },
        "blinkieBoxBackgrounds": {
          "cardBgUrl": "/card-backgrounds/red-lips.gif"
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a5",
      "is_visible": true
    },
    {
      "card_type": "text",
      "title": "LINK",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "scatterLayouts": {
          "system-settings": {
            "x": 68.95522388059702,
            "y": 203.03462686567167,
            "width": 100,
            "height": 10,
            "zIndex": 78
          }
        },
        "transparentBackground": true
      },
      "size": "small",
      "position": "center",
      "sortKey": "a6",
      "is_visible": true
    },
    {
      "card_type": "text",
      "title": "LINK",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "scatterLayouts": {
          "system-settings": {
            "x": 7.761194029850746,
            "y": 198.9782089552239,
            "width": 100,
            "height": 10,
            "zIndex": 79
          }
        },
        "transparentBackground": true
      },
      "size": "small",
      "position": "center",
      "sortKey": "a7",
      "is_visible": true
    },
    {
      "card_type": "text",
      "title": "LINK",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "verticalAlign": "middle",
        "scatterLayouts": {
          "system-settings": {
            "x": 17.300985074626865,
            "y": 53.826567164179096,
            "width": 201.57539385993394,
            "zIndex": 70
          }
        }
      },
      "size": "big",
      "position": "center",
      "sortKey": "a8",
      "is_visible": true
    },
    {
      "card_type": "text",
      "title": "YOUR NAME",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "verticalAlign": "middle",
        "scatterLayouts": {
          "system-settings": {
            "x": 54.435222154952235,
            "y": 0,
            "width": 162.385112532883,
            "zIndex": 72
          }
        }
      },
      "size": "big",
      "position": "center",
      "sortKey": "a9",
      "is_visible": true
    },
    {
      "card_type": "text",
      "title": "LINK",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "verticalAlign": "middle",
        "scatterLayouts": {
          "system-settings": {
            "x": 39.40298507462687,
            "y": 203.50746268656715,
            "zIndex": 60
          }
        }
      },
      "size": "big",
      "position": "center",
      "sortKey": "aA",
      "is_visible": true
    },
    {
      "card_type": "text",
      "title": "LINK",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "verticalAlign": "middle",
        "scatterLayouts": {
          "system-settings": {
            "x": 44.6595223880597,
            "y": 173.5710447761194,
            "zIndex": 84,
            "width": 192.26424798242704
          }
        }
      },
      "size": "big",
      "position": "center",
      "sortKey": "aB",
      "is_visible": true
    }
  ],
  "theme": {
    "themeId": "system-settings",
    "paletteId": null,
    "colors": {
      "background": "#b70000",
      "cardBg": "#9bdde0",
      "text": "#ffffff",
      "accent": "#9bdde0",
      "border": "#ffffff",
      "link": "#ffffff",
      "titleBarLine": "#ffffff"
    },
    "fonts": {
      "body": "var(--font-dm-sans)",
      "heading": "var(--font-ishmeria)",
      "bodySize": 1,
      "headingSize": 1,
      "headingWeight": "normal"
    },
    "style": {
      "borderRadius": 6,
      "blurIntensity": 0,
      "shadowEnabled": false
    },
    "background": {
      "type": "solid",
      "value": "#b70000"
    },
    "cardTypeFontSizes": {
      "hero": 1,
      "square": 1,
      "horizontal": 1,
      "link": 1,
      "mini": 1,
      "text": 1.3,
      "gallery": 1,
      "video": 1
    },
    "centerCards": false,
    "vcrCenterContent": false,
    "receiptPrice": "PRICELESS",
    "receiptStickers": [],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": false,
    "ipodStickers": [],
    "ipodTexture": "/images/metal-texture.jpeg",
    "ipodFont": "system",
    "macPattern": "",
    "macPatternColor": "#c0c0c0",
    "wordArtTitleStyle": "style-eleven",
    "phoneHomeDock": [],
    "phoneHomeShowDock": true,
    "phoneHomeVariant": "default",
    "zineBadgeText": "NEW!",
    "zineTitleSize": 1,
    "zineShowDoodles": true,
    "artifactMarqueeText": "LINKS_DATABASE /// ACCESS_GRANTED >>> CONNECT_NOW /// NET_RUNNER",
    "artifactHeaderTopLeft": "USER.ID_99",
    "artifactHeaderTopCenter": "[ONLINE]",
    "artifactHeaderTopRight": "",
    "artifactHeaderBottomLeft": "DIGITAL // PHY",
    "artifactHeaderBottomCenter": "///",
    "artifactHeaderBottomRight": "SYS_ADMIN",
    "artifactShowHeaderMeta": true,
    "artifactHeroOverlay": true,
    "artifactHeroMediaType": "image",
    "artifactHeroImageUrl": "",
    "artifactHeroVideoUrl": "",
    "artifactHeroPositionX": 50,
    "artifactHeroPositionY": 50,
    "scatterMode": true,
    "visitorDrag": false
  },
  "profile": {
    "displayName": "YOUR NAME",
    "bio": null,
    "avatarUrl": null,
    "avatarFeather": 0,
    "showAvatar": false,
    "showTitle": false,
    "titleSize": "small",
    "showSocialIcons": true,
    "showLogo": false,
    "logoUrl": null,
    "logoScale": 100,
    "profileLayout": "classic",
    "headerTextColor": "#ffffff",
    "socialIconColor": "#ffffff",
    "socialIcons": [
      {
        "id": "1757f885-bebc-4bd3-9962-177d8aa6c3ba",
        "platform": "instagram",
        "url": "",
        "sortKey": "a0"
      },
      {
        "id": "7b5b63b1-4169-4075-b2b3-cdbc0472802a",
        "platform": "bandcamp",
        "url": "",
        "sortKey": "a1"
      },
      {
        "id": "5c8e9f53-b73b-404e-98dc-49ca133d6d2b",
        "platform": "spotify",
        "url": "",
        "sortKey": "a2"
      },
      {
        "id": "83fc5d2f-2d05-4e01-8106-d255fa70c886",
        "platform": "applemusic",
        "url": "",
        "sortKey": "a3"
      }
    ]
  },
  "mediaAssets": [],
  "id": "system-settings-spread-them-out",
  "name": "SPREAD THEM OUT",
  "description": "SPREAD THEM OUT template",
  "thumbnailPath": "/templates/system-settings-spread-them-out/thumbnail.jpg"
} as const satisfies TemplateDefinition
