// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const systemSettingsThreeSACrowd: TemplateDefinition = {
  "themeId": "system-settings",
  "cards": [
    {
      "card_type": "video",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "videoZoom": 1.2,
        "videoPositionX": 50,
        "videoPositionY": 50,
        "uploadedVideoUrl": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-videos/444be064-08a1-4513-8706-efb98c2f1547/2b373fd2-0dfc-4585-b9f9-3715162e5c93.mp4",
        "uploadedVideoPath": "444be064-08a1-4513-8706-efb98c2f1547/2b373fd2-0dfc-4585-b9f9-3715162e5c93.mp4",
        "transparentBackground": true
      },
      "size": "big",
      "position": "left",
      "sortKey": "a3",
      "is_visible": true
    },
    {
      "card_type": "text",
      "title": "LINK",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "transparentBackground": true
      },
      "size": "small",
      "position": "center",
      "sortKey": "a4",
      "is_visible": true
    },
    {
      "card_type": "text",
      "title": "LINK",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "transparentBackground": true
      },
      "size": "small",
      "position": "center",
      "sortKey": "a5",
      "is_visible": true
    }
  ],
  "theme": {
    "themeId": "system-settings",
    "paletteId": null,
    "colors": {
      "background": "#000000",
      "cardBg": "#122d81",
      "text": "#dedec7",
      "accent": "#122d81",
      "border": "#dedec7",
      "link": "#dedec7",
      "titleBarLine": "#dedec7"
    },
    "fonts": {
      "body": "var(--font-dm-sans)",
      "heading": "var(--font-ishmeria)",
      "bodySize": 1,
      "headingSize": 1,
      "headingWeight": "normal"
    },
    "style": {
      "borderRadius": 6,
      "blurIntensity": 0,
      "shadowEnabled": false
    },
    "background": {
      "type": "solid",
      "value": "#000000"
    },
    "cardTypeFontSizes": {
      "hero": 1,
      "square": 1,
      "horizontal": 1,
      "link": 1,
      "mini": 1,
      "text": 1.3,
      "gallery": 1,
      "video": 1
    },
    "centerCards": true,
    "vcrCenterContent": false,
    "receiptPrice": "PRICELESS",
    "receiptStickers": [],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": false,
    "ipodStickers": [],
    "ipodTexture": "/images/metal-texture.jpeg",
    "ipodFont": "system",
    "macPattern": "",
    "macPatternColor": "#c0c0c0",
    "wordArtTitleStyle": "style-eleven",
    "phoneHomeDock": [],
    "phoneHomeShowDock": true,
    "phoneHomeDockTranslucent": true,
    "phoneHomeVariant": "default",
    "zineBadgeText": "NEW!",
    "zineTitleSize": 1,
    "zineShowDoodles": true,
    "artifactMarqueeText": "LINKS_DATABASE /// ACCESS_GRANTED >>> CONNECT_NOW /// NET_RUNNER",
    "artifactHeaderTopLeft": "USER.ID_99",
    "artifactHeaderTopCenter": "[ONLINE]",
    "artifactHeaderTopRight": "",
    "artifactHeaderBottomLeft": "DIGITAL // PHY",
    "artifactHeaderBottomCenter": "///",
    "artifactHeaderBottomRight": "SYS_ADMIN",
    "artifactShowHeaderMeta": true,
    "artifactHeroOverlay": true,
    "artifactHeroMediaType": "image",
    "artifactHeroImageUrl": "",
    "artifactHeroVideoUrl": "",
    "artifactHeroPositionX": 50,
    "artifactHeroPositionY": 50,
    "scatterMode": false,
    "visitorDrag": false
  },
  "profile": {
    "displayName": "YOUR NAME",
    "bio": null,
    "avatarUrl": null,
    "avatarFeather": 0,
    "showAvatar": false,
    "showTitle": false,
    "titleSize": "small",
    "showSocialIcons": true,
    "showLogo": false,
    "logoUrl": null,
    "logoScale": 100,
    "profileLayout": "classic",
    "headerTextColor": "#dedec7",
    "socialIconColor": "#dedec7",
    "socialIcons": []
  },
  "mediaAssets": [],
  "id": "system-settings-three-s-a-crowd",
  "name": "THREE'S A CROWD",
  "description": "THREE'S A CROWD template",
  "thumbnailPath": "/templates/system-settings-three-s-a-crowd/thumbnail.jpg"
} as const satisfies TemplateDefinition
