// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const blinkiesBlinkOnce: TemplateDefinition = {
  "themeId": "blinkies",
  "cards": [
    {
      "card_type": "link",
      "title": "MUSIC",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "blinkieStyle": "0250-redbouncyhearts",
        "verticalAlign": "middle"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a0",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "VIDEOS",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "blinkieStyle": "0213-gradientorange",
        "verticalAlign": "middle"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a1",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "MERCH",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "blinkieStyle": "0106-vicioussmiley",
        "verticalAlign": "middle"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a2",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "YOU TWIN",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "blinkieStyle": "0022-iheart",
        "verticalAlign": "middle"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a4",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "SHOWS",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "blinkieStyle": "0018-glitter",
        "verticalAlign": "middle"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a5",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "MAILING LIST",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "blinkieStyle": "0242-loveletter",
        "verticalAlign": "middle"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a6",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "PRESAVE ",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "blinkieStyle": "0187-transparentsparkle",
        "verticalAlign": "middle"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a6V",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "INSTAGRAM",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "blinkieStyle": "0089-kiss",
        "verticalAlign": "middle"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a6l",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "WEBSITE",
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "blinkieStyle": "0028-computer",
        "verticalAlign": "middle"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a6t",
      "is_visible": true
    }
  ],
  "theme": {
    "themeId": "blinkies",
    "paletteId": "poolsuite-pink",
    "colors": {
      "link": "oklch(0.35 0.12 250)",
      "text": "oklch(0 0 0)",
      "accent": "oklch(1 0 0)",
      "border": "oklch(0.20 0 0)",
      "cardBg": "oklch(0.95 0.02 70)",
      "background": "oklch(0.89 0.04 10)"
    },
    "fonts": {
      "body": "var(--font-dm-sans)",
      "heading": "var(--font-ishmeria)",
      "bodySize": 1,
      "headingSize": 1,
      "headingWeight": "normal"
    },
    "style": {
      "borderRadius": 6,
      "blurIntensity": 0,
      "shadowEnabled": false
    },
    "background": {
      "type": "image",
      "value": "https://blvmwpxltwittctoatfd.supabase.co/storage/v1/object/public/card-images/36eb6d57-7a64-458a-aafa-16e076ead485/backgrounds/1771576720790.jpg",
      "dimOverlay": true,
      "dimIntensity": 45
    },
    "cardTypeFontSizes": {
      "hero": 1,
      "square": 1,
      "horizontal": 1,
      "link": 1,
      "mini": 1,
      "text": 1.3,
      "gallery": 1,
      "video": 1
    },
    "centerCards": false,
    "vcrCenterContent": false,
    "receiptPrice": "PRICELESS",
    "receiptStickers": [],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": false,
    "ipodStickers": [],
    "ipodTexture": "/images/metal-texture.jpeg",
    "ipodFont": "system",
    "macPattern": "",
    "macPatternColor": "#c0c0c0",
    "wordArtTitleStyle": "style-eleven",
    "phoneHomeDock": [],
    "phoneHomeShowDock": true,
    "phoneHomeVariant": "default",
    "zineBadgeText": "NEW!",
    "zineTitleSize": 1,
    "zineShowDoodles": true,
    "artifactMarqueeText": "LINKS_DATABASE /// ACCESS_GRANTED >>> CONNECT_NOW /// NET_RUNNER",
    "artifactHeaderTopLeft": "USER.ID_99",
    "artifactHeaderTopCenter": "[ONLINE]",
    "artifactHeaderTopRight": "",
    "artifactHeaderBottomLeft": "DIGITAL // PHY",
    "artifactHeaderBottomCenter": "///",
    "artifactHeaderBottomRight": "SYS_ADMIN",
    "artifactShowHeaderMeta": true,
    "artifactHeroOverlay": true,
    "artifactHeroMediaType": "image",
    "artifactHeroImageUrl": "",
    "artifactHeroVideoUrl": "",
    "artifactHeroPositionX": 50,
    "artifactHeroPositionY": 50,
    "scatterMode": false,
    "visitorDrag": false
  },
  "profile": {
    "displayName": "YOUR NAME",
    "bio": null,
    "avatarUrl": null,
    "avatarFeather": 0,
    "showAvatar": false,
    "showTitle": false,
    "titleSize": "small",
    "showSocialIcons": true,
    "showLogo": false,
    "logoUrl": null,
    "logoScale": 100,
    "profileLayout": "classic",
    "headerTextColor": "oklch(0 0 0)",
    "socialIconColor": "#ffffff",
    "socialIcons": [
      {
        "id": "1757f885-bebc-4bd3-9962-177d8aa6c3ba",
        "url": "",
        "sortKey": "a0",
        "platform": "instagram"
      },
      {
        "id": "7b5b63b1-4169-4075-b2b3-cdbc0472802a",
        "url": "",
        "sortKey": "a1",
        "platform": "bandcamp"
      },
      {
        "id": "5c8e9f53-b73b-404e-98dc-49ca133d6d2b",
        "url": "",
        "sortKey": "a2",
        "platform": "spotify"
      },
      {
        "id": "83fc5d2f-2d05-4e01-8106-d255fa70c886",
        "url": "",
        "sortKey": "a3",
        "platform": "applemusic"
      },
      {
        "id": "151ff72d-08e7-43ee-b0d5-2739392a0fda",
        "platform": "website",
        "url": "",
        "sortKey": "a4"
      }
    ]
  },
  "mediaAssets": [],
  "id": "blinkies-blink-once",
  "name": "BLINK ONCE",
  "description": "BLINK ONCE template",
  "thumbnailPath": "/templates/blinkies-blink-once/thumbnail.jpg"
} as const satisfies TemplateDefinition
