// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const blinkiesMakeItRed: TemplateDefinition = {
  "themeId": "blinkies",
  "cards": [
    {
      "card_type": "link",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "blinkieStyle": "0241-redpulse",
        "verticalAlign": "middle"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a6",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "blinkieStyle": "0241-redpulse",
        "verticalAlign": "middle"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a7",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "blinkieStyle": "0241-redpulse",
        "verticalAlign": "middle"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a8",
      "is_visible": true
    },
    {
      "card_type": "audio",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "tracks": [],
        "looping": false,
        "reverbConfig": {
          "mix": 0.3,
          "damp": 0.5,
          "width": 0.8,
          "enabled": false,
          "roomSize": 0.5,
          "predelayMs": 20
        },
        "showWaveform": true,
        "blinkieColors": {
          "text": "#be0000",
          "buttons": "#000000",
          "innerBox": "#000000",
          "outerBox": "#000000",
          "playerBox": "#000000"
        },
        "scatterLayouts": {
          "blinkies": {
            "x": 0,
            "y": 89.53611940298508,
            "width": 75.67150917753528,
            "height": 10,
            "zIndex": 88
          },
          "instagram-reels": {
            "x": 0,
            "y": 89.53611940298508,
            "width": 75.67150917753528,
            "height": 10,
            "zIndex": 88
          },
          "system-settings": {
            "x": 0,
            "y": 89.53611940298508,
            "width": 75.67150917753528,
            "height": 10,
            "zIndex": 88
          }
        },
        "blinkieBoxBackgrounds": {
          "cardBgNone": true
        },
        "transparentBackground": false
      },
      "size": "big",
      "position": "left",
      "sortKey": "a9V",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "blinkieStyle": "0241-redpulse",
        "verticalAlign": "middle"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a9d",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "blinkieStyle": "0241-redpulse",
        "verticalAlign": "middle"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a9l",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": null,
      "description": null,
      "url": null,
      "content": {
        "textAlign": "center",
        "blinkieStyle": "0241-redpulse",
        "verticalAlign": "middle"
      },
      "size": "big",
      "position": "left",
      "sortKey": "a9t",
      "is_visible": true
    },
    {
      "card_type": "social-icons",
      "title": null,
      "description": null,
      "url": null,
      "content": {},
      "size": "big",
      "position": "left",
      "sortKey": "aA",
      "is_visible": true
    }
  ],
  "theme": {
    "themeId": "blinkies",
    "paletteId": "poolsuite-pink",
    "colors": {
      "link": "oklch(0.35 0.12 250)",
      "text": "oklch(0 0 0)",
      "accent": "oklch(1 0 0)",
      "border": "oklch(0.20 0 0)",
      "cardBg": "oklch(0.95 0.02 70)",
      "background": "#000000"
    },
    "fonts": {
      "body": "var(--font-dm-sans)",
      "heading": "var(--font-ishmeria)",
      "bodySize": 1,
      "headingSize": 1,
      "headingWeight": "normal"
    },
    "style": {
      "borderRadius": 6,
      "blurIntensity": 0,
      "shadowEnabled": false
    },
    "background": {
      "type": "solid",
      "value": "#000000",
      "dimOverlay": true,
      "dimIntensity": 45
    },
    "cardTypeFontSizes": {
      "hero": 1,
      "square": 1,
      "horizontal": 1,
      "link": 1,
      "mini": 1,
      "text": 1.3,
      "gallery": 1,
      "video": 1
    },
    "centerCards": false,
    "vcrCenterContent": false,
    "receiptPrice": "PRICELESS",
    "receiptStickers": [],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": false,
    "ipodStickers": [],
    "ipodTexture": "/images/metal-texture.jpeg",
    "ipodFont": "system",
    "macPattern": "",
    "macPatternColor": "#c0c0c0",
    "wordArtTitleStyle": "style-eleven",
    "phoneHomeDock": [],
    "phoneHomeShowDock": true,
    "phoneHomeVariant": "default",
    "zineBadgeText": "NEW!",
    "zineTitleSize": 1,
    "zineShowDoodles": true,
    "artifactMarqueeText": "LINKS_DATABASE /// ACCESS_GRANTED >>> CONNECT_NOW /// NET_RUNNER",
    "artifactHeaderTopLeft": "USER.ID_99",
    "artifactHeaderTopCenter": "[ONLINE]",
    "artifactHeaderTopRight": "",
    "artifactHeaderBottomLeft": "DIGITAL // PHY",
    "artifactHeaderBottomCenter": "///",
    "artifactHeaderBottomRight": "SYS_ADMIN",
    "artifactShowHeaderMeta": true,
    "artifactHeroOverlay": true,
    "artifactHeroMediaType": "image",
    "artifactHeroImageUrl": "",
    "artifactHeroVideoUrl": "",
    "artifactHeroPositionX": 50,
    "artifactHeroPositionY": 50,
    "scatterMode": false,
    "visitorDrag": false
  },
  "profile": {
    "displayName": "YOUR NAME",
    "bio": null,
    "avatarUrl": null,
    "avatarFeather": 0,
    "showAvatar": false,
    "showTitle": false,
    "titleSize": "small",
    "showSocialIcons": true,
    "showLogo": false,
    "logoUrl": null,
    "logoScale": 100,
    "profileLayout": "classic",
    "headerTextColor": "oklch(0 0 0)",
    "socialIconColor": "#b70000",
    "socialIcons": [
      {
        "id": "1757f885-bebc-4bd3-9962-177d8aa6c3ba",
        "url": "",
        "sortKey": "a0",
        "platform": "instagram"
      },
      {
        "id": "7b5b63b1-4169-4075-b2b3-cdbc0472802a",
        "url": "",
        "sortKey": "a1",
        "platform": "bandcamp"
      },
      {
        "id": "5c8e9f53-b73b-404e-98dc-49ca133d6d2b",
        "url": "",
        "sortKey": "a2",
        "platform": "spotify"
      },
      {
        "id": "83fc5d2f-2d05-4e01-8106-d255fa70c886",
        "url": "",
        "sortKey": "a3",
        "platform": "applemusic"
      },
      {
        "id": "151ff72d-08e7-43ee-b0d5-2739392a0fda",
        "platform": "website",
        "url": "",
        "sortKey": "a4"
      }
    ]
  },
  "mediaAssets": [],
  "id": "blinkies-make-it-red",
  "name": "MAKE IT RED",
  "description": "MAKE IT RED template",
  "thumbnailPath": "/templates/blinkies-make-it-red/thumbnail.jpg"
} as const satisfies TemplateDefinition
