// Auto-generated by DevTemplateSaver
import type { TemplateDefinition } from '../../types'

export const vcrMenuHomeVideo: TemplateDefinition = {
  "themeId": "vcr-menu",
  "cards": [
    {
      "card_type": "social-icons",
      "title": null,
      "description": null,
      "url": null,
      "content": {},
      "size": "big",
      "position": "left",
      "sortKey": "a0",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": "LISTEN",
      "description": null,
      "url": "https://open.spotify.com/album/",
      "content": {
        "iconName": "Music",
        "textAlign": "center",
        "showButton": false
      },
      "size": "small",
      "position": "center",
      "sortKey": "a1",
      "is_visible": true
    },
    {
      "card_type": "hero",
      "title": "VIDEOS",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin",
        "textAlign": "center",
        "showButton": false
      },
      "size": "small",
      "position": "center",
      "sortKey": "a2",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "TOUR DATES",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin"
      },
      "size": "big",
      "position": "center",
      "sortKey": "a6",
      "is_visible": true
    },
    {
      "card_type": "link",
      "title": "MERCH",
      "description": null,
      "url": "https://bandsintown.com/",
      "content": {
        "iconName": "MapPin"
      },
      "size": "big",
      "position": "center",
      "sortKey": "a7",
      "is_visible": true
    }
  ],
  "theme": {
    "themeId": "vcr-menu",
    "paletteId": "classic-vcr",
    "colors": {
      "background": "#000562",
      "cardBg": "#000562",
      "text": "#d8daba",
      "accent": "#000562",
      "border": "#000562",
      "link": "#d8daba"
    },
    "fonts": {
      "heading": "var(--font-pixter-granular)",
      "body": "var(--font-pixter-granular)",
      "headingSize": 3,
      "bodySize": 1.63,
      "headingWeight": "normal"
    },
    "style": {
      "borderRadius": 0,
      "shadowEnabled": false,
      "blurIntensity": 0
    },
    "background": {
      "type": "solid",
      "value": "#000562"
    },
    "cardTypeFontSizes": {
      "hero": 0.8,
      "square": 1,
      "horizontal": 1,
      "link": 1.2,
      "mini": 1,
      "text": 1,
      "gallery": 1,
      "video": 1
    },
    "centerCards": false,
    "vcrCenterContent": false,
    "receiptPrice": "PRICELESS",
    "receiptStickers": [],
    "receiptFloatAnimation": true,
    "receiptPaperTexture": false,
    "ipodStickers": [],
    "ipodTexture": "/images/metal-texture.jpeg",
    "ipodFont": "system",
    "macPattern": "",
    "macPatternColor": "#c0c0c0",
    "wordArtTitleStyle": "style-eleven",
    "phoneHomeDock": [],
    "phoneHomeShowDock": true,
    "phoneHomeVariant": "default",
    "zineBadgeText": "NEW!",
    "zineTitleSize": 1,
    "zineShowDoodles": true,
    "artifactMarqueeText": "LINKS_DATABASE /// ACCESS_GRANTED >>> CONNECT_NOW /// NET_RUNNER",
    "artifactHeaderTopLeft": "USER.ID_99",
    "artifactHeaderTopCenter": "[ONLINE]",
    "artifactHeaderTopRight": "",
    "artifactHeaderBottomLeft": "DIGITAL // PHY",
    "artifactHeaderBottomCenter": "///",
    "artifactHeaderBottomRight": "SYS_ADMIN",
    "artifactShowHeaderMeta": true,
    "artifactHeroOverlay": true,
    "artifactHeroMediaType": "image",
    "artifactHeroImageUrl": "",
    "artifactHeroVideoUrl": "",
    "artifactHeroPositionX": 50,
    "artifactHeroPositionY": 50,
    "scatterMode": false,
    "visitorDrag": false
  },
  "profile": {
    "displayName": "YOUR NAME",
    "bio": null,
    "avatarUrl": null,
    "avatarFeather": 0,
    "showAvatar": true,
    "showTitle": true,
    "titleSize": "small",
    "showSocialIcons": true,
    "showLogo": false,
    "logoUrl": null,
    "logoScale": 100,
    "profileLayout": "classic",
    "headerTextColor": "#ffffff",
    "socialIconColor": "#ffffff",
    "socialIcons": [
      {
        "id": "d720a696-fcb5-4ec2-aa37-a5ca2e749027",
        "url": "",
        "sortKey": "a0",
        "platform": "twitter"
      },
      {
        "id": "86ec3c07-a25a-4aaf-b063-98ae75cf1fa8",
        "url": "",
        "sortKey": "a1",
        "platform": "instagram"
      },
      {
        "id": "144c3a93-9040-471f-86d9-cacda54921ff",
        "url": "",
        "sortKey": "a2",
        "platform": "spotify"
      },
      {
        "id": "8d4ad2df-d302-4e46-a9f6-a4f19633c261",
        "url": "",
        "sortKey": "a3",
        "platform": "tiktok"
      }
    ]
  },
  "mediaAssets": [],
  "id": "vcr-menu-home-video",
  "name": "HOME VIDEO",
  "description": "HOME VIDEO template",
  "thumbnailPath": "/templates/vcr-menu-home-video/thumbnail.jpg"
} as const satisfies TemplateDefinition
